In [85]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import rcParams
from matplotlib.cm import rainbow

import warnings
warnings.filterwarnings('ignore')

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

In [86]:
dataset = pd.read_csv('healthcare-dataset-stroke-data(3).csv')

In [87]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 5000 non-null   int64
 1   gender             5000 non-null   object
 2   age                5000 non-null   float64
 3   hypertension       5000 non-null   int64
 4   heart_disease      5000 non-null   int64
 5   ever_married       5000 non-null   object
 6   work_type          5000 non-null   object
 7   Residence_type     5000 non-null   object
 8   avg_glucose_level  5000 non-null   float64
 9   bmi                4425 non-null   float64
 10  smoking_status     5000 non-null   object
 11  stroke             5000 non-null   int64
 12  Heart Rate         5000 non-null   int64
 13  SpO2               5000 non-null   int64
dtypes: float64(3), int64(6), object(5)
memory usage: 547.0+ KB

In [88]:
dataset

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke,Heart Rate,SpO2
0,51314,Female,78.0,0,0,Yes,Private,Urban,106.74,33.0,formerly smoked,1,75,94
1,33175,Female,57.0,0,0,Yes,Govt_job,Urban,110.52,28.5,Unknown,1,96,91
2,66638,Female,68.0,1,0,No,Self-employed,Urban,79.79,29.7,never smoked,1,60,98
3,49130,Male,74.0,0,0,Yes,Private,Urban,98.55,25.6,Unknown,1,94,98
4,8154,Male,57.0,1,0,Yes,Govt_job,Urban,78.92,27.7,formerly smoked,1,67,90
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,30116,Female,57.0,0,0,Yes,Private,Rural,102.28,25.5,never smoked,0,66,99
4996,19773,Female,52.0,0,0,Yes,Private,Rural,96.59,26.4,never smoked,1,84,99
4997,72081,Female,57.0,1,0,Yes,Govt_job,Rural,67.41,32.9,never smoked,1,70,95
4998,46688,Female,44.0,0,0,No,Private,Urban,127.21,29.8,smokes,0,90,91
4999,7937,Male,60.0,1,0,Yes,Govt_job,Urban,213.03,20.2,smokes,1,87,99

In [89]:
#dataset=dataset.replace(to_replace='?',value='0')

In [90]:
print('Finding missing values')
print(dataset.isnull().sum())

Finding missing values
id                     0
gender                 0
age                    0
hypertension           0
heart_disease          0
ever_married           0
work_type              0
Residence_type         0
avg_glucose_level      0
bmi                  575
smoking_status         0
stroke                 0
Heart Rate             0
SpO2                   0
dtype: int64

In [91]:
#dataset['id']=dataset['id'].dataset(dataset['id'].mean())
dataset['bmi']=dataset['bmi'].fillna(dataset['bmi'].mean()) 
#dataset

In [92]:
print('Finding missing values')
print(dataset.isnull().sum())

Finding missing values
id                   0
gender               0
age                  0
hypertension         0
heart_disease        0
ever_married         0
work_type            0
Residence_type       0
avg_glucose_level    0
bmi                  0
smoking_status       0
stroke               0
Heart Rate           0
SpO2                 0
dtype: int64

In [93]:
dataset = dataset.dropna()
dataset

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke,Heart Rate,SpO2
0,51314,Female,78.0,0,0,Yes,Private,Urban,106.74,33.0,formerly smoked,1,75,94
1,33175,Female,57.0,0,0,Yes,Govt_job,Urban,110.52,28.5,Unknown,1,96,91
2,66638,Female,68.0,1,0,No,Self-employed,Urban,79.79,29.7,never smoked,1,60,98
3,49130,Male,74.0,0,0,Yes,Private,Urban,98.55,25.6,Unknown,1,94,98
4,8154,Male,57.0,1,0,Yes,Govt_job,Urban,78.92,27.7,formerly smoked,1,67,90
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,30116,Female,57.0,0,0,Yes,Private,Rural,102.28,25.5,never smoked,0,66,99
4996,19773,Female,52.0,0,0,Yes,Private,Rural,96.59,26.4,never smoked,1,84,99
4997,72081,Female,57.0,1,0,Yes,Govt_job,Rural,67.41,32.9,never smoked,1,70,95
4998,46688,Female,44.0,0,0,No,Private,Urban,127.21,29.8,smokes,0,90,91
4999,7937,Male,60.0,1,0,Yes,Govt_job,Urban,213.03,20.2,smokes,1,87,99

In [94]:
from sklearn.preprocessing import LabelEncoder

labelencoder_X = LabelEncoder()

dataset['gender'] = labelencoder_X.fit_transform(dataset['gender'])
dataset['ever_married'] = labelencoder_X.fit_transform(dataset['ever_married'])
dataset['work_type'] = labelencoder_X.fit_transform(dataset['work_type'])
dataset['Residence_type'] = labelencoder_X.fit_transform(dataset['Residence_type'])
dataset['smoking_status'] = labelencoder_X.fit_transform(dataset['smoking_status'])

In [95]:
dataset

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke,Heart Rate,SpO2
0,51314,0,78.0,0,0,1,2,1,106.74,33.0,1,1,75,94
1,33175,0,57.0,0,0,1,0,1,110.52,28.5,0,1,96,91
2,66638,0,68.0,1,0,0,3,1,79.79,29.7,2,1,60,98
3,49130,1,74.0,0,0,1,2,1,98.55,25.6,0,1,94,98
4,8154,1,57.0,1,0,1,0,1,78.92,27.7,1,1,67,90
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,30116,0,57.0,0,0,1,2,0,102.28,25.5,2,0,66,99
4996,19773,0,52.0,0,0,1,2,0,96.59,26.4,2,1,84,99
4997,72081,0,57.0,1,0,1,0,0,67.41,32.9,2,1,70,95
4998,46688,0,44.0,0,0,0,2,1,127.21,29.8,3,0,90,91
4999,7937,1,60.0,1,0,1,0,1,213.03,20.2,3,1,87,99

In [96]:
y = dataset['stroke']
X = dataset.drop(['stroke'], axis = 1)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.35, random_state = 0)

In [97]:
gnb = GaussianNB()

In [98]:
#Train the model using the training sets
gnb.fit(X_train, y_train)

GaussianNB()

In [99]:
X_test

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,Heart Rate,SpO2
398,64523,1,54.0,1,0,1,2,1,89.93,32.100000,2,96,95
3833,32503,0,80.0,0,0,1,3,1,76.57,34.100000,2,92,93
4836,42072,0,50.0,1,0,1,2,0,73.18,30.300000,1,99,91
4572,11933,0,79.0,0,0,1,2,0,169.67,29.676475,0,84,94
636,39912,0,32.0,0,0,1,2,0,76.13,29.900000,3,91,100
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1458,54574,0,20.0,0,0,0,2,1,115.69,29.200000,2,95,91
1941,29552,0,55.0,1,1,1,2,1,210.40,40.000000,3,100,100
4882,45277,0,74.0,0,0,1,2,0,231.61,34.600000,1,82,95
1984,43717,1,57.0,1,0,1,2,1,212.08,44.200000,3,62,96
1445,52216,0,35.0,0,0,1,2,1,87.72,21.300000,2,74,95

In [100]:
#Predict the response for test dataset
y_pred = gnb.predict(X_test)
for i in range(0, len(y_pred)):
    i2=str(i)
    res=''
    if y_pred[i]==0:
        res='normal'
    elif y_pred[i]==1:
        res='Stroke'
    print('Test data ',i2 , ' is ',res)

Test data  0  is  Stroke
Test data  1  is  Stroke
Test data  2  is  Stroke
Test data  3  is  Stroke
Test data  4  is  normal
Test data  5  is  Stroke
Test data  6  is  Stroke
Test data  7  is  Stroke
Test data  8  is  Stroke
Test data  9  is  normal
Test data  10  is  Stroke
Test data  11  is  Stroke
Test data  12  is  Stroke
Test data  13  is  Stroke
Test data  14  is  Stroke
Test data  15  is  Stroke
Test data  16  is  normal
Test data  17  is  Stroke
Test data  18  is  Stroke
Test data  19  is  Stroke
Test data  20  is  Stroke
Test data  21  is  normal
Test data  22  is  Stroke
Test data  23  is  Stroke
Test data  24  is  Stroke
Test data  25  is  normal
Test data  26  is  Stroke
Test data  27  is  Stroke
Test data  28  is  Stroke
Test data  29  is  Stroke
Test data  30  is  normal
Test data  31  is  Stroke
Test data  32  is  Stroke
Test data  33  is  Stroke
Test data  34  is  Stroke
Test data  35  is  normal
Test data  36  is  Stroke
Test data  37  is  Stroke
Test data  38  is  Stroke
Test data  39  is  Stroke
Test data  40  is  Stroke
Test data  41  is  Stroke
Test data  42  is  Stroke
Test data  43  is  normal
Test data  44  is  Stroke
Test data  45  is  Stroke
Test data  46  is  normal
Test data  47  is  Stroke
Test data  48  is  normal
Test data  49  is  Stroke
Test data  50  is  Stroke
Test data  51  is  Stroke
Test data  52  is  Stroke
Test data  53  is  Stroke
Test data  54  is  Stroke
Test data  55  is  Stroke
Test data  56  is  Stroke
Test data  57  is  Stroke
Test data  58  is  Stroke
Test data  59  is  Stroke
Test data  60  is  Stroke
Test data  61  is  normal
Test data  62  is  Stroke
Test data  63  is  Stroke
Test data  64  is  Stroke
Test data  65  is  Stroke
Test data  66  is  Stroke
Test data  67  is  normal
Test data  68  is  Stroke
Test data  69  is  normal
Test data  70  is  Stroke
Test data  71  is  Stroke
Test data  72  is  Stroke
Test data  73  is  normal
Test data  74  is  Stroke
Test data  75  is  Stroke
Test data  76  is  Stroke
Test data  77  is  Stroke
Test data  78  is  Stroke
Test data  79  is  normal
Test data  80  is  Stroke
Test data  81  is  Stroke
Test data  82  is  normal
Test data  83  is  Stroke
Test data  84  is  Stroke
Test data  85  is  normal
Test data  86  is  Stroke
Test data  87  is  Stroke
Test data  88  is  normal
Test data  89  is  Stroke
Test data  90  is  Stroke
Test data  91  is  normal
Test data  92  is  Stroke
Test data  93  is  Stroke
Test data  94  is  Stroke
Test data  95  is  Stroke
Test data  96  is  Stroke
Test data  97  is  normal
Test data  98  is  Stroke
Test data  99  is  Stroke
Test data  100  is  Stroke
Test data  101  is  normal
Test data  102  is  Stroke
Test data  103  is  Stroke
Test data  104  is  Stroke
Test data  105  is  normal
Test data  106  is  Stroke
Test data  107  is  normal
Test data  108  is  Stroke
Test data  109  is  normal
Test data  110  is  Stroke
Test data  111  is  Stroke
Test data  112  is  Stroke
Test data  113  is  Stroke
Test data  114  is  Stroke
Test data  115  is  Stroke
Test data  116  is  Stroke
Test data  117  is  Stroke
Test data  118  is  normal
Test data  119  is  Stroke
Test data  120  is  Stroke
Test data  121  is  normal
Test data  122  is  Stroke
Test data  123  is  normal
Test data  124  is  normal
Test data  125  is  Stroke
Test data  126  is  normal
Test data  127  is  Stroke
Test data  128  is  normal
Test data  129  is  Stroke
Test data  130  is  Stroke
Test data  131  is  normal
Test data  132  is  Stroke
Test data  133  is  normal
Test data  134  is  Stroke
Test data  135  is  normal
Test data  136  is  Stroke
Test data  137  is  Stroke
Test data  138  is  Stroke
Test data  139  is  Stroke
Test data  140  is  Stroke
Test data  141  is  normal
Test data  142  is  Stroke
Test data  143  is  Stroke
Test data  144  is  Stroke
Test data  145  is  Stroke
Test data  146  is  Stroke
Test data  147  is  normal
Test data  148  is  Stroke
Test data  149  is  normal
Test data  150  is  Stroke
Test data  151  is  Stroke
Test data  152  is  normal
Test data  153  is  Stroke
Test data  154  is  normal
Test data  155  is  Stroke
Test data  156  is  Stroke
Test data  157  is  Stroke
Test data  158  is  Stroke
Test data  159  is  Stroke
Test data  160  is  normal
Test data  161  is  normal
Test data  162  is  Stroke
Test data  163  is  Stroke
Test data  164  is  Stroke
Test data  165  is  normal
Test data  166  is  Stroke
Test data  167  is  Stroke
Test data  168  is  Stroke
Test data  169  is  Stroke
Test data  170  is  normal
Test data  171  is  Stroke
Test data  172  is  Stroke
Test data  173  is  Stroke
Test data  174  is  Stroke
Test data  175  is  Stroke
Test data  176  is  Stroke
Test data  177  is  normal
Test data  178  is  Stroke
Test data  179  is  normal
Test data  180  is  Stroke
Test data  181  is  Stroke
Test data  182  is  normal
Test data  183  is  normal
Test data  184  is  normal
Test data  185  is  normal
Test data  186  is  normal
Test data  187  is  Stroke
Test data  188  is  Stroke
Test data  189  is  Stroke
Test data  190  is  normal
Test data  191  is  Stroke
Test data  192  is  normal
Test data  193  is  normal
Test data  194  is  normal
Test data  195  is  Stroke
Test data  196  is  Stroke
Test data  197  is  normal
Test data  198  is  normal
Test data  199  is  Stroke
Test data  200  is  normal
Test data  201  is  normal
Test data  202  is  Stroke
Test data  203  is  Stroke
Test data  204  is  Stroke
Test data  205  is  Stroke
Test data  206  is  Stroke
Test data  207  is  Stroke
Test data  208  is  Stroke
Test data  209  is  Stroke
Test data  210  is  Stroke
Test data  211  is  Stroke
Test data  212  is  Stroke
Test data  213  is  Stroke
Test data  214  is  Stroke
Test data  215  is  normal
Test data  216  is  normal
Test data  217  is  Stroke
Test data  218  is  Stroke
Test data  219  is  Stroke
Test data  220  is  normal
Test data  221  is  Stroke
Test data  222  is  normal
Test data  223  is  Stroke
Test data  224  is  Stroke
Test data  225  is  Stroke
Test data  226  is  normal
Test data  227  is  Stroke
Test data  228  is  Stroke
Test data  229  is  normal
Test data  230  is  normal
Test data  231  is  Stroke
Test data  232  is  Stroke
Test data  233  is  Stroke
Test data  234  is  Stroke
Test data  235  is  Stroke
Test data  236  is  Stroke
Test data  237  is  Stroke
Test data  238  is  Stroke
Test data  239  is  Stroke
Test data  240  is  Stroke
Test data  241  is  normal
Test data  242  is  Stroke
Test data  243  is  Stroke
Test data  244  is  Stroke
Test data  245  is  normal
Test data  246  is  Stroke
Test data  247  is  Stroke
Test data  248  is  Stroke
Test data  249  is  Stroke
Test data  250  is  Stroke
Test data  251  is  normal
Test data  252  is  Stroke
Test data  253  is  Stroke
Test data  254  is  Stroke
Test data  255  is  Stroke
Test data  256  is  Stroke
Test data  257  is  Stroke
Test data  258  is  Stroke
Test data  259  is  normal
Test data  260  is  Stroke
Test data  261  is  Stroke
Test data  262  is  Stroke
Test data  263  is  Stroke
Test data  264  is  Stroke
Test data  265  is  normal
Test data  266  is  normal
Test data  267  is  Stroke
Test data  268  is  normal
Test data  269  is  Stroke
Test data  270  is  Stroke
Test data  271  is  Stroke
Test data  272  is  Stroke
Test data  273  is  Stroke
Test data  274  is  Stroke
Test data  275  is  Stroke
Test data  276  is  normal
Test data  277  is  Stroke
Test data  278  is  Stroke
Test data  279  is  Stroke
Test data  280  is  Stroke
Test data  281  is  Stroke
Test data  282  is  Stroke
Test data  283  is  Stroke
Test data  284  is  Stroke
Test data  285  is  Stroke
Test data  286  is  Stroke
Test data  287  is  normal
Test data  288  is  Stroke
Test data  289  is  normal
Test data  290  is  Stroke
Test data  291  is  Stroke
Test data  292  is  Stroke
Test data  293  is  normal
Test data  294  is  Stroke
Test data  295  is  Stroke
Test data  296  is  Stroke
Test data  297  is  Stroke
Test data  298  is  normal
Test data  299  is  Stroke
Test data  300  is  normal
Test data  301  is  normal
Test data  302  is  Stroke
Test data  303  is  Stroke
Test data  304  is  Stroke
Test data  305  is  Stroke
Test data  306  is  Stroke
Test data  307  is  normal
Test data  308  is  Stroke
Test data  309  is  Stroke
Test data  310  is  Stroke
Test data  311  is  Stroke
Test data  312  is  Stroke
Test data  313  is  normal
Test data  314  is  Stroke
Test data  315  is  Stroke
Test data  316  is  normal
Test data  317  is  Stroke
Test data  318  is  Stroke
Test data  319  is  Stroke
Test data  320  is  Stroke
Test data  321  is  Stroke
Test data  322  is  Stroke
Test data  323  is  Stroke
Test data  324  is  normal
Test data  325  is  Stroke
Test data  326  is  Stroke
Test data  327  is  Stroke
Test data  328  is  Stroke
Test data  329  is  Stroke
Test data  330  is  normal
Test data  331  is  Stroke
Test data  332  is  Stroke
Test data  333  is  Stroke
Test data  334  is  Stroke
Test data  335  is  Stroke
Test data  336  is  Stroke
Test data  337  is  Stroke
Test data  338  is  Stroke
Test data  339  is  Stroke
Test data  340  is  normal
Test data  341  is  Stroke
Test data  342  is  Stroke
Test data  343  is  Stroke
Test data  344  is  Stroke
Test data  345  is  Stroke
Test data  346  is  Stroke
Test data  347  is  Stroke
Test data  348  is  Stroke
Test data  349  is  Stroke
Test data  350  is  Stroke
Test data  351  is  Stroke
Test data  352  is  Stroke
Test data  353  is  Stroke
Test data  354  is  Stroke
Test data  355  is  Stroke
Test data  356  is  Stroke
Test data  357  is  Stroke
Test data  358  is  Stroke
Test data  359  is  Stroke
Test data  360  is  Stroke
Test data  361  is  Stroke
Test data  362  is  Stroke
Test data  363  is  normal
Test data  364  is  Stroke
Test data  365  is  normal
Test data  366  is  Stroke
Test data  367  is  Stroke
Test data  368  is  Stroke
Test data  369  is  Stroke
Test data  370  is  Stroke
Test data  371  is  normal
Test data  372  is  Stroke
Test data  373  is  normal
Test data  374  is  Stroke
Test data  375  is  Stroke
Test data  376  is  Stroke
Test data  377  is  Stroke
Test data  378  is  Stroke
Test data  379  is  Stroke
Test data  380  is  Stroke
Test data  381  is  Stroke
Test data  382  is  Stroke
Test data  383  is  normal
Test data  384  is  normal
Test data  385  is  Stroke
Test data  386  is  Stroke
Test data  387  is  normal
Test data  388  is  normal
Test data  389  is  normal
Test data  390  is  Stroke
Test data  391  is  Stroke
Test data  392  is  normal
Test data  393  is  Stroke
Test data  394  is  Stroke
Test data  395  is  normal
Test data  396  is  Stroke
Test data  397  is  Stroke
Test data  398  is  Stroke
Test data  399  is  Stroke
Test data  400  is  Stroke
Test data  401  is  Stroke
Test data  402  is  normal
Test data  403  is  normal
Test data  404  is  normal
Test data  405  is  Stroke
Test data  406  is  Stroke
Test data  407  is  Stroke
Test data  408  is  normal
Test data  409  is  Stroke
Test data  410  is  Stroke
Test data  411  is  Stroke
Test data  412  is  Stroke
Test data  413  is  Stroke
Test data  414  is  Stroke
Test data  415  is  normal
Test data  416  is  Stroke
Test data  417  is  Stroke
Test data  418  is  Stroke
Test data  419  is  Stroke
Test data  420  is  Stroke
Test data  421  is  Stroke
Test data  422  is  Stroke
Test data  423  is  Stroke
Test data  424  is  Stroke
Test data  425  is  Stroke
Test data  426  is  normal
Test data  427  is  normal
Test data  428  is  Stroke
Test data  429  is  Stroke
Test data  430  is  Stroke
Test data  431  is  Stroke
Test data  432  is  normal
Test data  433  is  Stroke
Test data  434  is  normal
Test data  435  is  Stroke
Test data  436  is  Stroke
Test data  437  is  normal
Test data  438  is  Stroke
Test data  439  is  Stroke
Test data  440  is  Stroke
Test data  441  is  Stroke
Test data  442  is  Stroke
Test data  443  is  Stroke
Test data  444  is  Stroke
Test data  445  is  Stroke
Test data  446  is  Stroke
Test data  447  is  normal
Test data  448  is  normal
Test data  449  is  normal
Test data  450  is  Stroke
Test data  451  is  normal
Test data  452  is  normal
Test data  453  is  normal
Test data  454  is  Stroke
Test data  455  is  Stroke
Test data  456  is  Stroke
Test data  457  is  Stroke
Test data  458  is  Stroke
Test data  459  is  Stroke
Test data  460  is  Stroke
Test data  461  is  normal
Test data  462  is  Stroke
Test data  463  is  Stroke
Test data  464  is  Stroke
Test data  465  is  Stroke
Test data  466  is  Stroke
Test data  467  is  Stroke
Test data  468  is  Stroke
Test data  469  is  Stroke
Test data  470  is  Stroke
Test data  471  is  Stroke
Test data  472  is  Stroke
Test data  473  is  normal
Test data  474  is  Stroke
Test data  475  is  normal
Test data  476  is  Stroke
Test data  477  is  Stroke
Test data  478  is  Stroke
Test data  479  is  normal
Test data  480  is  Stroke
Test data  481  is  Stroke
Test data  482  is  Stroke
Test data  483  is  Stroke
Test data  484  is  Stroke
Test data  485  is  Stroke
Test data  486  is  Stroke
Test data  487  is  Stroke
Test data  488  is  Stroke
Test data  489  is  Stroke
Test data  490  is  normal
Test data  491  is  normal
Test data  492  is  normal
Test data  493  is  Stroke
Test data  494  is  normal
Test data  495  is  normal
Test data  496  is  Stroke
Test data  497  is  Stroke
Test data  498  is  Stroke
Test data  499  is  Stroke
Test data  500  is  Stroke
Test data  501  is  normal
Test data  502  is  Stroke
Test data  503  is  Stroke
Test data  504  is  normal
Test data  505  is  Stroke
Test data  506  is  normal
Test data  507  is  normal
Test data  508  is  normal
Test data  509  is  normal
Test data  510  is  normal
Test data  511  is  Stroke
Test data  512  is  Stroke
Test data  513  is  Stroke
Test data  514  is  Stroke
Test data  515  is  Stroke
Test data  516  is  normal
Test data  517  is  Stroke
Test data  518  is  Stroke
Test data  519  is  Stroke
Test data  520  is  Stroke
Test data  521  is  Stroke
Test data  522  is  Stroke
Test data  523  is  Stroke
Test data  524  is  Stroke
Test data  525  is  Stroke
Test data  526  is  normal
Test data  527  is  Stroke
Test data  528  is  Stroke
Test data  529  is  Stroke
Test data  530  is  Stroke
Test data  531  is  normal
Test data  532  is  normal
Test data  533  is  normal
Test data  534  is  Stroke
Test data  535  is  normal
Test data  536  is  normal
Test data  537  is  normal
Test data  538  is  Stroke
Test data  539  is  Stroke
Test data  540  is  Stroke
Test data  541  is  Stroke
Test data  542  is  Stroke
Test data  543  is  Stroke
Test data  544  is  Stroke
Test data  545  is  Stroke
Test data  546  is  Stroke
Test data  547  is  Stroke
Test data  548  is  Stroke
Test data  549  is  Stroke
Test data  550  is  normal
Test data  551  is  normal
Test data  552  is  Stroke
Test data  553  is  Stroke
Test data  554  is  normal
Test data  555  is  normal
Test data  556  is  Stroke
Test data  557  is  Stroke
Test data  558  is  Stroke
Test data  559  is  Stroke
Test data  560  is  normal
Test data  561  is  normal
Test data  562  is  normal
Test data  563  is  Stroke
Test data  564  is  normal
Test data  565  is  Stroke
Test data  566  is  normal
Test data  567  is  normal
Test data  568  is  normal
Test data  569  is  Stroke
Test data  570  is  Stroke
Test data  571  is  Stroke
Test data  572  is  Stroke
Test data  573  is  Stroke
Test data  574  is  normal
Test data  575  is  normal
Test data  576  is  Stroke
Test data  577  is  Stroke
Test data  578  is  normal
Test data  579  is  normal
Test data  580  is  normal
Test data  581  is  normal
Test data  582  is  Stroke
Test data  583  is  normal
Test data  584  is  normal
Test data  585  is  Stroke
Test data  586  is  Stroke
Test data  587  is  normal
Test data  588  is  Stroke
Test data  589  is  Stroke
Test data  590  is  Stroke
Test data  591  is  Stroke
Test data  592  is  Stroke
Test data  593  is  normal
Test data  594  is  Stroke
Test data  595  is  Stroke
Test data  596  is  Stroke
Test data  597  is  normal
Test data  598  is  Stroke
Test data  599  is  normal
Test data  600  is  Stroke
Test data  601  is  Stroke
Test data  602  is  Stroke
Test data  603  is  normal
Test data  604  is  normal
Test data  605  is  Stroke
Test data  606  is  Stroke
Test data  607  is  Stroke
Test data  608  is  normal
Test data  609  is  normal
Test data  610  is  Stroke
Test data  611  is  Stroke
Test data  612  is  Stroke
Test data  613  is  Stroke
Test data  614  is  Stroke
Test data  615  is  Stroke
Test data  616  is  Stroke
Test data  617  is  normal
Test data  618  is  normal
Test data  619  is  normal
Test data  620  is  Stroke
Test data  621  is  normal
Test data  622  is  normal
Test data  623  is  Stroke
Test data  624  is  Stroke
Test data  625  is  Stroke
Test data  626  is  Stroke
Test data  627  is  normal
Test data  628  is  Stroke
Test data  629  is  Stroke
Test data  630  is  Stroke
Test data  631  is  Stroke
Test data  632  is  Stroke
Test data  633  is  normal
Test data  634  is  Stroke
Test data  635  is  Stroke
Test data  636  is  normal
Test data  637  is  Stroke
Test data  638  is  Stroke
Test data  639  is  Stroke
Test data  640  is  normal
Test data  641  is  Stroke
Test data  642  is  Stroke
Test data  643  is  Stroke
Test data  644  is  Stroke
Test data  645  is  normal
Test data  646  is  Stroke
Test data  647  is  normal
Test data  648  is  Stroke
Test data  649  is  Stroke
Test data  650  is  normal
Test data  651  is  Stroke
Test data  652  is  Stroke
Test data  653  is  Stroke
Test data  654  is  Stroke
Test data  655  is  Stroke
Test data  656  is  Stroke
Test data  657  is  Stroke
Test data  658  is  Stroke
Test data  659  is  Stroke
Test data  660  is  Stroke
Test data  661  is  Stroke
Test data  662  is  normal
Test data  663  is  Stroke
Test data  664  is  normal
Test data  665  is  Stroke
Test data  666  is  normal
Test data  667  is  Stroke
Test data  668  is  Stroke
Test data  669  is  Stroke
Test data  670  is  Stroke
Test data  671  is  Stroke
Test data  672  is  Stroke
Test data  673  is  Stroke
Test data  674  is  Stroke
Test data  675  is  Stroke
Test data  676  is  normal
Test data  677  is  normal
Test data  678  is  Stroke
Test data  679  is  Stroke
Test data  680  is  Stroke
Test data  681  is  Stroke
Test data  682  is  Stroke
Test data  683  is  Stroke
Test data  684  is  Stroke
Test data  685  is  normal
Test data  686  is  Stroke
Test data  687  is  Stroke
Test data  688  is  Stroke
Test data  689  is  Stroke
Test data  690  is  Stroke
Test data  691  is  Stroke
Test data  692  is  Stroke
Test data  693  is  Stroke
Test data  694  is  Stroke
Test data  695  is  Stroke
Test data  696  is  Stroke
Test data  697  is  Stroke
Test data  698  is  Stroke
Test data  699  is  Stroke
Test data  700  is  Stroke
Test data  701  is  Stroke
Test data  702  is  Stroke
Test data  703  is  Stroke
Test data  704  is  normal
Test data  705  is  Stroke
Test data  706  is  Stroke
Test data  707  is  Stroke
Test data  708  is  Stroke
Test data  709  is  normal
Test data  710  is  Stroke
Test data  711  is  normal
Test data  712  is  Stroke
Test data  713  is  Stroke
Test data  714  is  Stroke
Test data  715  is  Stroke
Test data  716  is  normal
Test data  717  is  Stroke
Test data  718  is  Stroke
Test data  719  is  Stroke
Test data  720  is  Stroke
Test data  721  is  Stroke
Test data  722  is  Stroke
Test data  723  is  Stroke
Test data  724  is  normal
Test data  725  is  normal
Test data  726  is  Stroke
Test data  727  is  Stroke
Test data  728  is  Stroke
Test data  729  is  Stroke
Test data  730  is  Stroke
Test data  731  is  Stroke
Test data  732  is  Stroke
Test data  733  is  Stroke
Test data  734  is  Stroke
Test data  735  is  Stroke
Test data  736  is  Stroke
Test data  737  is  Stroke
Test data  738  is  Stroke
Test data  739  is  Stroke
Test data  740  is  Stroke
Test data  741  is  normal
Test data  742  is  Stroke
Test data  743  is  Stroke

In [101]:
print(confusion_matrix(y_test,y_pred))

[[ 352  248]
 [  85 1065]]

In [102]:
from sklearn import metrics
print("Accuracy for Naive Bayes Classifier : {}%".format(metrics.accuracy_score(y_test, y_pred)*100))

Accuracy for Naive Bayes Classifier : 80.97142857142858%

In [103]:
from sklearn.svm import SVC

In [104]:
#svclassifier = SVC(kernel='linear')
svclassifier = SVC()
svclassifier.fit(X_train, y_train)

SVC()

In [105]:
y_pred = svclassifier.predict(X_test)
for i in range(0, len(y_pred)):
    i2=str(i)
    res=''
    if y_pred[i]==0:
        res='normal'
    elif y_pred[i]==1:
        res='Stroke'
    print('Test data ',i2 , ' is ',res)

Test data  0  is  Stroke
Test data  1  is  Stroke
Test data  2  is  Stroke
Test data  3  is  Stroke
Test data  4  is  Stroke
Test data  5  is  Stroke
Test data  6  is  Stroke
Test data  7  is  Stroke
Test data  8  is  Stroke
Test data  9  is  Stroke
Test data  10  is  Stroke
Test data  11  is  Stroke
Test data  12  is  Stroke
Test data  13  is  Stroke
Test data  14  is  Stroke
Test data  15  is  Stroke
Test data  16  is  Stroke
Test data  17  is  Stroke
Test data  18  is  Stroke
Test data  19  is  Stroke
Test data  20  is  Stroke
Test data  21  is  Stroke
Test data  22  is  Stroke
Test data  23  is  Stroke
Test data  24  is  Stroke
Test data  25  is  Stroke
Test data  26  is  Stroke
Test data  27  is  Stroke
Test data  28  is  Stroke
Test data  29  is  Stroke
Test data  30  is  Stroke
Test data  31  is  Stroke
Test data  32  is  Stroke
Test data  33  is  Stroke
Test data  34  is  Stroke
Test data  35  is  Stroke
Test data  36  is  Stroke
Test data  37  is  Stroke
Test data  38  is  Stroke
Test data  39  is  Stroke
Test data  40  is  Stroke
Test data  41  is  Stroke
Test data  42  is  Stroke
Test data  43  is  Stroke
Test data  44  is  Stroke
Test data  45  is  Stroke
Test data  46  is  Stroke
Test data  47  is  Stroke
Test data  48  is  Stroke
Test data  49  is  Stroke
Test data  50  is  Stroke
Test data  51  is  Stroke
Test data  52  is  Stroke
Test data  53  is  Stroke
Test data  54  is  Stroke
Test data  55  is  Stroke
Test data  56  is  Stroke
Test data  57  is  Stroke
Test data  58  is  Stroke
Test data  59  is  Stroke
Test data  60  is  Stroke
Test data  61  is  Stroke
Test data  62  is  Stroke
Test data  63  is  Stroke
Test data  64  is  Stroke
Test data  65  is  Stroke
Test data  66  is  Stroke
Test data  67  is  Stroke
Test data  68  is  Stroke
Test data  69  is  Stroke
Test data  70  is  Stroke
Test data  71  is  Stroke
Test data  72  is  Stroke
Test data  73  is  Stroke
Test data  74  is  Stroke
Test data  75  is  Stroke
Test data  76  is  Stroke
Test data  77  is  Stroke
Test data  78  is  Stroke
Test data  79  is  Stroke
Test data  80  is  Stroke
Test data  81  is  Stroke
Test data  82  is  Stroke
Test data  83  is  Stroke
Test data  84  is  Stroke
Test data  85  is  Stroke
Test data  86  is  Stroke
Test data  87  is  Stroke
Test data  88  is  Stroke
Test data  89  is  Stroke
Test data  90  is  Stroke
Test data  91  is  Stroke
Test data  92  is  Stroke
Test data  93  is  Stroke
Test data  94  is  Stroke
Test data  95  is  Stroke
Test data  96  is  Stroke
Test data  97  is  Stroke
Test data  98  is  Stroke
Test data  99  is  Stroke
Test data  100  is  Stroke
Test data  101  is  Stroke
Test data  102  is  Stroke
Test data  103  is  Stroke
Test data  104  is  Stroke
Test data  105  is  Stroke
Test data  106  is  Stroke
Test data  107  is  Stroke
Test data  108  is  Stroke
Test data  109  is  Stroke
Test data  110  is  Stroke
Test data  111  is  Stroke
Test data  112  is  Stroke
Test data  113  is  Stroke
Test data  114  is  Stroke
Test data  115  is  Stroke
Test data  116  is  Stroke
Test data  117  is  Stroke
Test data  118  is  Stroke
Test data  119  is  Stroke
Test data  120  is  Stroke
Test data  121  is  Stroke
Test data  122  is  Stroke
Test data  123  is  Stroke
Test data  124  is  Stroke
Test data  125  is  Stroke
Test data  126  is  Stroke
Test data  127  is  Stroke
Test data  128  is  Stroke
Test data  129  is  Stroke
Test data  130  is  Stroke
Test data  131  is  Stroke
Test data  132  is  Stroke
Test data  133  is  Stroke
Test data  134  is  Stroke
Test data  135  is  Stroke
Test data  136  is  Stroke
Test data  137  is  Stroke
Test data  138  is  Stroke
Test data  139  is  Stroke
Test data  140  is  Stroke
Test data  141  is  Stroke
Test data  142  is  Stroke
Test data  143  is  Stroke
Test data  144  is  Stroke
Test data  145  is  Stroke
Test data  146  is  Stroke
Test data  147  is  Stroke
Test data  148  is  Stroke
Test data  149  is  Stroke
Test data  150  is  Stroke
Test data  151  is  Stroke
Test data  152  is  Stroke
Test data  153  is  Stroke
Test data  154  is  Stroke
Test data  155  is  Stroke
Test data  156  is  Stroke
Test data  157  is  Stroke
Test data  158  is  Stroke
Test data  159  is  Stroke
Test data  160  is  Stroke
Test data  161  is  Stroke
Test data  162  is  Stroke
Test data  163  is  Stroke
Test data  164  is  Stroke
Test data  165  is  Stroke
Test data  166  is  Stroke
Test data  167  is  Stroke
Test data  168  is  Stroke
Test data  169  is  Stroke
Test data  170  is  Stroke
Test data  171  is  Stroke
Test data  172  is  Stroke
Test data  173  is  Stroke
Test data  174  is  Stroke
Test data  175  is  Stroke
Test data  176  is  Stroke
Test data  177  is  Stroke
Test data  178  is  Stroke
Test data  179  is  Stroke
Test data  180  is  Stroke
Test data  181  is  Stroke
Test data  182  is  Stroke
Test data  183  is  Stroke
Test data  184  is  Stroke
Test data  185  is  Stroke
Test data  186  is  Stroke
Test data  187  is  Stroke
Test data  188  is  Stroke
Test data  189  is  Stroke
Test data  190  is  Stroke
Test data  191  is  Stroke
Test data  192  is  Stroke
Test data  193  is  Stroke
Test data  194  is  Stroke
Test data  195  is  Stroke
Test data  196  is  Stroke
Test data  197  is  Stroke
Test data  198  is  Stroke
Test data  199  is  Stroke
Test data  200  is  Stroke
Test data  201  is  Stroke
Test data  202  is  Stroke
Test data  203  is  Stroke
Test data  204  is  Stroke
Test data  205  is  Stroke
Test data  206  is  Stroke
Test data  207  is  Stroke
Test data  208  is  Stroke
Test data  209  is  Stroke
Test data  210  is  Stroke
Test data  211  is  Stroke
Test data  212  is  Stroke
Test data  213  is  Stroke
Test data  214  is  Stroke
Test data  215  is  Stroke
Test data  216  is  Stroke
Test data  217  is  Stroke
Test data  218  is  Stroke
Test data  219  is  Stroke
Test data  220  is  Stroke
Test data  221  is  Stroke
Test data  222  is  Stroke
Test data  223  is  Stroke
Test data  224  is  Stroke
Test data  225  is  Stroke
Test data  226  is  Stroke
Test data  227  is  Stroke
Test data  228  is  Stroke
Test data  229  is  Stroke
Test data  230  is  Stroke
Test data  231  is  Stroke
Test data  232  is  Stroke
Test data  233  is  Stroke
Test data  234  is  Stroke
Test data  235  is  Stroke
Test data  236  is  Stroke
Test data  237  is  Stroke
Test data  238  is  Stroke
Test data  239  is  Stroke
Test data  240  is  Stroke
Test data  241  is  Stroke
Test data  242  is  Stroke
Test data  243  is  Stroke
Test data  244  is  Stroke
Test data  245  is  Stroke
Test data  246  is  Stroke
Test data  247  is  Stroke
Test data  248  is  Stroke
Test data  249  is  Stroke
Test data  250  is  Stroke
Test data  251  is  Stroke
Test data  252  is  Stroke
Test data  253  is  Stroke
Test data  254  is  Stroke
Test data  255  is  Stroke
Test data  256  is  Stroke
Test data  257  is  Stroke
Test data  258  is  Stroke
Test data  259  is  Stroke
Test data  260  is  Stroke
Test data  261  is  Stroke
Test data  262  is  Stroke
Test data  263  is  Stroke
Test data  264  is  Stroke
Test data  265  is  Stroke
Test data  266  is  Stroke
Test data  267  is  Stroke
Test data  268  is  Stroke
Test data  269  is  Stroke
Test data  270  is  Stroke
Test data  271  is  Stroke
Test data  272  is  Stroke
Test data  273  is  Stroke
Test data  274  is  Stroke
Test data  275  is  Stroke
Test data  276  is  Stroke
Test data  277  is  Stroke
Test data  278  is  Stroke
Test data  279  is  Stroke
Test data  280  is  Stroke
Test data  281  is  Stroke
Test data  282  is  Stroke
Test data  283  is  Stroke
Test data  284  is  Stroke
Test data  285  is  Stroke
Test data  286  is  Stroke
Test data  287  is  Stroke
Test data  288  is  Stroke
Test data  289  is  Stroke
Test data  290  is  Stroke
Test data  291  is  Stroke
Test data  292  is  Stroke
Test data  293  is  Stroke
Test data  294  is  Stroke
Test data  295  is  Stroke
Test data  296  is  Stroke
Test data  297  is  Stroke
Test data  298  is  Stroke
Test data  299  is  Stroke
Test data  300  is  Stroke
Test data  301  is  Stroke
Test data  302  is  Stroke
Test data  303  is  Stroke
Test data  304  is  Stroke
Test data  305  is  Stroke
Test data  306  is  Stroke
Test data  307  is  Stroke
Test data  308  is  Stroke
Test data  309  is  Stroke
Test data  310  is  Stroke
Test data  311  is  Stroke
Test data  312  is  Stroke
Test data  313  is  Stroke
Test data  314  is  Stroke
Test data  315  is  Stroke
Test data  316  is  Stroke
Test data  317  is  Stroke
Test data  318  is  Stroke
Test data  319  is  Stroke
Test data  320  is  Stroke
Test data  321  is  Stroke
Test data  322  is  Stroke
Test data  323  is  Stroke
Test data  324  is  Stroke
Test data  325  is  Stroke
Test data  326  is  Stroke
Test data  327  is  Stroke
Test data  328  is  Stroke
Test data  329  is  Stroke
Test data  330  is  Stroke
Test data  331  is  Stroke
Test data  332  is  Stroke
Test data  333  is  Stroke
Test data  334  is  Stroke
Test data  335  is  Stroke
Test data  336  is  Stroke
Test data  337  is  Stroke
Test data  338  is  Stroke
Test data  339  is  Stroke
Test data  340  is  Stroke
Test data  341  is  Stroke
Test data  342  is  Stroke
Test data  343  is  Stroke
Test data  344  is  Stroke
Test data  345  is  Stroke
Test data  346  is  Stroke
Test data  347  is  Stroke
Test data  348  is  Stroke
Test data  349  is  Stroke
Test data  350  is  Stroke
Test data  351  is  Stroke
Test data  352  is  Stroke
Test data  353  is  Stroke
Test data  354  is  Stroke
Test data  355  is  Stroke
Test data  356  is  Stroke
Test data  357  is  Stroke
Test data  358  is  Stroke
Test data  359  is  Stroke
Test data  360  is  Stroke
Test data  361  is  Stroke
Test data  362  is  Stroke
Test data  363  is  Stroke
Test data  364  is  Stroke
Test data  365  is  Stroke
Test data  366  is  Stroke
Test data  367  is  Stroke
Test data  368  is  Stroke
Test data  369  is  Stroke
Test data  370  is  Stroke
Test data  371  is  Stroke
Test data  372  is  Stroke
Test data  373  is  Stroke
Test data  374  is  Stroke
Test data  375  is  Stroke
Test data  376  is  Stroke
Test data  377  is  Stroke
Test data  378  is  Stroke
Test data  379  is  Stroke
Test data  380  is  Stroke
Test data  381  is  Stroke
Test data  382  is  Stroke
Test data  383  is  Stroke
Test data  384  is  Stroke
Test data  385  is  Stroke
Test data  386  is  Stroke
Test data  387  is  Stroke
Test data  388  is  Stroke
Test data  389  is  Stroke
Test data  390  is  Stroke
Test data  391  is  Stroke
Test data  392  is  Stroke
Test data  393  is  Stroke
Test data  394  is  Stroke
Test data  395  is  Stroke
Test data  396  is  Stroke
Test data  397  is  Stroke
Test data  398  is  Stroke
Test data  399  is  Stroke
Test data  400  is  Stroke
Test data  401  is  Stroke
Test data  402  is  Stroke
Test data  403  is  Stroke
Test data  404  is  Stroke
Test data  405  is  Stroke
Test data  406  is  Stroke
Test data  407  is  Stroke
Test data  408  is  Stroke
Test data  409  is  Stroke
Test data  410  is  Stroke
Test data  411  is  Stroke
Test data  412  is  Stroke
Test data  413  is  Stroke
Test data  414  is  Stroke
Test data  415  is  Stroke
Test data  416  is  Stroke
Test data  417  is  Stroke
Test data  418  is  Stroke
Test data  419  is  Stroke
Test data  420  is  Stroke
Test data  421  is  Stroke
Test data  422  is  Stroke
Test data  423  is  Stroke
Test data  424  is  Stroke
Test data  425  is  Stroke
Test data  426  is  Stroke
Test data  427  is  Stroke
Test data  428  is  Stroke
Test data  429  is  Stroke
Test data  430  is  Stroke
Test data  431  is  Stroke
Test data  432  is  Stroke
Test data  433  is  Stroke
Test data  434  is  Stroke
Test data  435  is  Stroke
Test data  436  is  Stroke
Test data  437  is  Stroke
Test data  438  is  Stroke
Test data  439  is  Stroke
Test data  440  is  Stroke
Test data  441  is  Stroke
Test data  442  is  Stroke
Test data  443  is  Stroke
Test data  444  is  Stroke
Test data  445  is  Stroke
Test data  446  is  Stroke
Test data  447  is  Stroke
Test data  448  is  Stroke
Test data  449  is  Stroke
Test data  450  is  Stroke
Test data  451  is  Stroke
Test data  452  is  Stroke
Test data  453  is  Stroke
Test data  454  is  Stroke
Test data  455  is  Stroke
Test data  456  is  Stroke
Test data  457  is  Stroke
Test data  458  is  Stroke
Test data  459  is  Stroke
Test data  460  is  Stroke
Test data  461  is  Stroke
Test data  462  is  Stroke
Test data  463  is  Stroke
Test data  464  is  Stroke
Test data  465  is  Stroke
Test data  466  is  Stroke
Test data  467  is  Stroke
Test data  468  is  Stroke
Test data  469  is  Stroke
Test data  470  is  Stroke
Test data  471  is  Stroke
Test data  472  is  Stroke
Test data  473  is  Stroke
Test data  474  is  Stroke
Test data  475  is  Stroke
Test data  476  is  Stroke
Test data  477  is  Stroke
Test data  478  is  Stroke
Test data  479  is  Stroke
Test data  480  is  Stroke
Test data  481  is  Stroke
Test data  482  is  Stroke
Test data  483  is  Stroke
Test data  484  is  Stroke
Test data  485  is  Stroke
Test data  486  is  Stroke
Test data  487  is  Stroke
Test data  488  is  Stroke
Test data  489  is  Stroke
Test data  490  is  Stroke
Test data  491  is  Stroke
Test data  492  is  Stroke
Test data  493  is  Stroke
Test data  494  is  Stroke
Test data  495  is  Stroke
Test data  496  is  Stroke
Test data  497  is  Stroke
Test data  498  is  Stroke
Test data  499  is  Stroke
Test data  500  is  Stroke
Test data  501  is  Stroke
Test data  502  is  Stroke
Test data  503  is  Stroke
Test data  504  is  Stroke
Test data  505  is  Stroke
Test data  506  is  Stroke
Test data  507  is  Stroke
Test data  508  is  Stroke
Test data  509  is  Stroke
Test data  510  is  Stroke
Test data  511  is  Stroke
Test data  512  is  Stroke
Test data  513  is  Stroke
Test data  514  is  Stroke
Test data  515  is  Stroke
Test data  516  is  Stroke
Test data  517  is  Stroke
Test data  518  is  Stroke
Test data  519  is  Stroke
Test data  520  is  Stroke
Test data  521  is  Stroke
Test data  522  is  Stroke
Test data  523  is  Stroke
Test data  524  is  Stroke
Test data  525  is  Stroke
Test data  526  is  Stroke
Test data  527  is  Stroke
Test data  528  is  Stroke
Test data  529  is  Stroke
Test data  530  is  Stroke
Test data  531  is  Stroke
Test data  532  is  Stroke
Test data  533  is  Stroke
Test data  534  is  Stroke
Test data  535  is  Stroke
Test data  536  is  Stroke
Test data  537  is  Stroke
Test data  538  is  Stroke
Test data  539  is  Stroke
Test data  540  is  Stroke
Test data  541  is  Stroke
Test data  542  is  Stroke
Test data  543  is  Stroke
Test data  544  is  Stroke
Test data  545  is  Stroke
Test data  546  is  Stroke
Test data  547  is  Stroke
Test data  548  is  Stroke
Test data  549  is  Stroke
Test data  550  is  Stroke
Test data  551  is  Stroke
Test data  552  is  Stroke
Test data  553  is  Stroke
Test data  554  is  Stroke
Test data  555  is  Stroke
Test data  556  is  Stroke
Test data  557  is  Stroke
Test data  558  is  Stroke
Test data  559  is  Stroke
Test data  560  is  Stroke
Test data  561  is  Stroke
Test data  562  is  Stroke
Test data  563  is  Stroke
Test data  564  is  Stroke
Test data  565  is  Stroke
Test data  566  is  Stroke
Test data  567  is  Stroke
Test data  568  is  Stroke
Test data  569  is  Stroke
Test data  570  is  Stroke
Test data  571  is  Stroke
Test data  572  is  Stroke
Test data  573  is  Stroke
Test data  574  is  Stroke
Test data  575  is  Stroke
Test data  576  is  Stroke
Test data  577  is  Stroke
Test data  578  is  Stroke
Test data  579  is  Stroke
Test data  580  is  Stroke
Test data  581  is  Stroke
Test data  582  is  Stroke
Test data  583  is  Stroke
Test data  584  is  Stroke
Test data  585  is  Stroke
Test data  586  is  Stroke
Test data  587  is  Stroke
Test data  588  is  Stroke
Test data  589  is  Stroke
Test data  590  is  Stroke
Test data  591  is  Stroke
Test data  592  is  Stroke
Test data  593  is  Stroke
Test data  594  is  Stroke
Test data  595  is  Stroke
Test data  596  is  Stroke
Test data  597  is  Stroke
Test data  598  is  Stroke
Test data  599  is  Stroke
Test data  600  is  Stroke
Test data  601  is  Stroke
Test data  602  is  Stroke
Test data  603  is  Stroke
Test data  604  is  Stroke
Test data  605  is  Stroke
Test data  606  is  Stroke
Test data  607  is  Stroke
Test data  608  is  Stroke
Test data  609  is  Stroke
Test data  610  is  Stroke
Test data  611  is  Stroke
Test data  612  is  Stroke
Test data  613  is  Stroke
Test data  614  is  Stroke
Test data  615  is  Stroke
Test data  616  is  Stroke
Test data  617  is  Stroke
Test data  618  is  Stroke
Test data  619  is  Stroke
Test data  620  is  Stroke
Test data  621  is  Stroke
Test data  622  is  Stroke
Test data  623  is  Stroke
Test data  624  is  Stroke
Test data  625  is  Stroke
Test data  626  is  Stroke
Test data  627  is  Stroke
Test data  628  is  Stroke
Test data  629  is  Stroke
Test data  630  is  Stroke
Test data  631  is  Stroke
Test data  632  is  Stroke
Test data  633  is  Stroke
Test data  634  is  Stroke
Test data  635  is  Stroke
Test data  636  is  Stroke
Test data  637  is  Stroke
Test data  638  is  Stroke
Test data  639  is  Stroke
Test data  640  is  Stroke
Test data  641  is  Stroke
Test data  642  is  Stroke
Test data  643  is  Stroke
Test data  644  is  Stroke
Test data  645  is  Stroke
Test data  646  is  Stroke
Test data  647  is  Stroke
Test data  648  is  Stroke
Test data  649  is  Stroke
Test data  650  is  Stroke
Test data  651  is  Stroke
Test data  652  is  Stroke
Test data  653  is  Stroke
Test data  654  is  Stroke
Test data  655  is  Stroke
Test data  656  is  Stroke
Test data  657  is  Stroke
Test data  658  is  Stroke
Test data  659  is  Stroke
Test data  660  is  Stroke
Test data  661  is  Stroke
Test data  662  is  Stroke
Test data  663  is  Stroke
Test data  664  is  Stroke
Test data  665  is  Stroke
Test data  666  is  Stroke
Test data  667  is  Stroke
Test data  668  is  Stroke
Test data  669  is  Stroke
Test data  670  is  Stroke
Test data  671  is  Stroke
Test data  672  is  Stroke
Test data  673  is  Stroke
Test data  674  is  Stroke
Test data  675  is  Stroke
Test data  676  is  Stroke
Test data  677  is  Stroke
Test data  678  is  Stroke
Test data  679  is  Stroke
Test data  680  is  Stroke
Test data  681  is  Stroke
Test data  682  is  Stroke
Test data  683  is  Stroke
Test data  684  is  Stroke
Test data  685  is  Stroke
Test data  686  is  Stroke
Test data  687  is  Stroke
Test data  688  is  Stroke
Test data  689  is  Stroke
Test data  690  is  Stroke
Test data  691  is  Stroke
Test data  692  is  Stroke
Test data  693  is  Stroke
Test data  694  is  Stroke
Test data  695  is  Stroke
Test data  696  is  Stroke
Test data  697  is  Stroke
Test data  698  is  Stroke
Test data  699  is  Stroke
Test data  700  is  Stroke
Test data  701  is  Stroke
Test data  702  is  Stroke
Test data  703  is  Stroke
Test data  704  is  Stroke
Test data  705  is  Stroke
Test data  706  is  Stroke
Test data  707  is  Stroke
Test data  708  is  Stroke
Test data  709  is  Stroke
Test data  710  is  Stroke
Test data  711  is  Stroke
Test data  712  is  Stroke
Test data  713  is  Stroke
Test data  714  is  Stroke
Test data  715  is  Stroke
Test data  716  is  Stroke
Test data  717  is  Stroke
Test data  718  is  Stroke
Test data  719  is  Stroke
Test data  720  is  Stroke
Test data  721  is  Stroke
Test data  722  is  Stroke
Test data  723  is  Stroke
Test data  724  is  Stroke
Test data  725  is  Stroke
Test data  726  is  Stroke
Test data  727  is  Stroke
Test data  728  is  Stroke
Test data  729  is  Stroke
Test data  730  is  Stroke
Test data  731  is  Stroke
Test data  732  is  Stroke
Test data  733  is  Stroke
Test data  734  is  Stroke
Test data  735  is  Stroke
Test data  736  is  Stroke
Test data  737  is  Stroke
Test data  738  is  Stroke
Test data  739  is  Stroke
Test data  740  is  Stroke
Test data  741  is  Stroke
Test data  742  is  Stroke
Test data  743  is  Stroke

In [106]:
print(confusion_matrix(y_test,y_pred))
#print(classification_report(y_test,y_pred))

[[   0  600]
 [   0 1150]]

In [107]:
print("Accuracy for SVM Classifier : {}%".format(metrics.accuracy_score(y_test, y_pred)*100))

Accuracy for SVM Classifier : 65.71428571428571%

In [108]:
from sklearn import linear_model

In [109]:
logr = linear_model.LogisticRegression()
logr.fit(X_train, y_train)

LogisticRegression()

In [110]:
y_pred = logr.predict(X_test)
for i in range(0, len(y_pred)):
    i2=str(i)
    res=''
    if y_pred[i]==0:
        res='normal'
    elif y_pred[i]==1:
        res='Stroke'
    print('Test data ',i2 , ' is ',res)

Test data  0  is  Stroke
Test data  1  is  Stroke
Test data  2  is  normal
Test data  3  is  Stroke
Test data  4  is  normal
Test data  5  is  Stroke
Test data  6  is  Stroke
Test data  7  is  Stroke
Test data  8  is  Stroke
Test data  9  is  normal
Test data  10  is  Stroke
Test data  11  is  Stroke
Test data  12  is  Stroke
Test data  13  is  Stroke
Test data  14  is  Stroke
Test data  15  is  Stroke
Test data  16  is  normal
Test data  17  is  Stroke
Test data  18  is  Stroke
Test data  19  is  Stroke
Test data  20  is  Stroke
Test data  21  is  normal
Test data  22  is  Stroke
Test data  23  is  Stroke
Test data  24  is  Stroke
Test data  25  is  normal
Test data  26  is  Stroke
Test data  27  is  Stroke
Test data  28  is  Stroke
Test data  29  is  Stroke
Test data  30  is  normal
Test data  31  is  Stroke
Test data  32  is  Stroke
Test data  33  is  Stroke
Test data  34  is  Stroke
Test data  35  is  normal
Test data  36  is  Stroke
Test data  37  is  Stroke
Test data  38  is  Stroke
Test data  39  is  Stroke
Test data  40  is  Stroke
Test data  41  is  Stroke
Test data  42  is  Stroke
Test data  43  is  normal
Test data  44  is  normal
Test data  45  is  Stroke
Test data  46  is  normal
Test data  47  is  Stroke
Test data  48  is  Stroke
Test data  49  is  Stroke
Test data  50  is  Stroke
Test data  51  is  Stroke
Test data  52  is  Stroke
Test data  53  is  Stroke
Test data  54  is  Stroke
Test data  55  is  Stroke
Test data  56  is  Stroke
Test data  57  is  Stroke
Test data  58  is  Stroke
Test data  59  is  Stroke
Test data  60  is  Stroke
Test data  61  is  normal
Test data  62  is  Stroke
Test data  63  is  Stroke
Test data  64  is  Stroke
Test data  65  is  Stroke
Test data  66  is  Stroke
Test data  67  is  normal
Test data  68  is  Stroke
Test data  69  is  normal
Test data  70  is  Stroke
Test data  71  is  Stroke
Test data  72  is  Stroke
Test data  73  is  Stroke
Test data  74  is  Stroke
Test data  75  is  Stroke
Test data  76  is  Stroke
Test data  77  is  Stroke
Test data  78  is  Stroke
Test data  79  is  normal
Test data  80  is  Stroke
Test data  81  is  Stroke
Test data  82  is  normal
Test data  83  is  Stroke
Test data  84  is  Stroke
Test data  85  is  normal
Test data  86  is  Stroke
Test data  87  is  Stroke
Test data  88  is  normal
Test data  89  is  Stroke
Test data  90  is  Stroke
Test data  91  is  normal
Test data  92  is  Stroke
Test data  93  is  Stroke
Test data  94  is  Stroke
Test data  95  is  Stroke
Test data  96  is  Stroke
Test data  97  is  Stroke
Test data  98  is  Stroke
Test data  99  is  Stroke
Test data  100  is  Stroke
Test data  101  is  normal
Test data  102  is  Stroke
Test data  103  is  Stroke
Test data  104  is  Stroke
Test data  105  is  normal
Test data  106  is  Stroke
Test data  107  is  normal
Test data  108  is  Stroke
Test data  109  is  normal
Test data  110  is  Stroke
Test data  111  is  Stroke
Test data  112  is  Stroke
Test data  113  is  Stroke
Test data  114  is  Stroke
Test data  115  is  Stroke
Test data  116  is  Stroke
Test data  117  is  Stroke
Test data  118  is  normal
Test data  119  is  Stroke
Test data  120  is  Stroke
Test data  121  is  normal
Test data  122  is  Stroke
Test data  123  is  normal
Test data  124  is  normal
Test data  125  is  Stroke
Test data  126  is  normal
Test data  127  is  Stroke
Test data  128  is  normal
Test data  129  is  Stroke
Test data  130  is  Stroke
Test data  131  is  normal
Test data  132  is  Stroke
Test data  133  is  normal
Test data  134  is  Stroke
Test data  135  is  Stroke
Test data  136  is  Stroke
Test data  137  is  Stroke
Test data  138  is  Stroke
Test data  139  is  Stroke
Test data  140  is  Stroke
Test data  141  is  normal
Test data  142  is  Stroke
Test data  143  is  Stroke
Test data  144  is  Stroke
Test data  145  is  Stroke
Test data  146  is  Stroke
Test data  147  is  normal
Test data  148  is  Stroke
Test data  149  is  normal
Test data  150  is  Stroke
Test data  151  is  Stroke
Test data  152  is  normal
Test data  153  is  Stroke
Test data  154  is  normal
Test data  155  is  Stroke
Test data  156  is  Stroke
Test data  157  is  Stroke
Test data  158  is  Stroke
Test data  159  is  Stroke
Test data  160  is  normal
Test data  161  is  normal
Test data  162  is  Stroke
Test data  163  is  Stroke
Test data  164  is  Stroke
Test data  165  is  normal
Test data  166  is  Stroke
Test data  167  is  Stroke
Test data  168  is  Stroke
Test data  169  is  Stroke
Test data  170  is  normal
Test data  171  is  Stroke
Test data  172  is  Stroke
Test data  173  is  Stroke
Test data  174  is  Stroke
Test data  175  is  Stroke
Test data  176  is  Stroke
Test data  177  is  normal
Test data  178  is  Stroke
Test data  179  is  normal
Test data  180  is  Stroke
Test data  181  is  Stroke
Test data  182  is  normal
Test data  183  is  normal
Test data  184  is  normal
Test data  185  is  normal
Test data  186  is  normal
Test data  187  is  Stroke
Test data  188  is  Stroke
Test data  189  is  Stroke
Test data  190  is  normal
Test data  191  is  Stroke
Test data  192  is  normal
Test data  193  is  normal
Test data  194  is  normal
Test data  195  is  Stroke
Test data  196  is  Stroke
Test data  197  is  normal
Test data  198  is  normal
Test data  199  is  Stroke
Test data  200  is  normal
Test data  201  is  normal
Test data  202  is  Stroke
Test data  203  is  Stroke
Test data  204  is  Stroke
Test data  205  is  Stroke
Test data  206  is  Stroke
Test data  207  is  normal
Test data  208  is  Stroke
Test data  209  is  Stroke
Test data  210  is  Stroke
Test data  211  is  Stroke
Test data  212  is  Stroke
Test data  213  is  Stroke
Test data  214  is  Stroke
Test data  215  is  normal
Test data  216  is  normal
Test data  217  is  Stroke
Test data  218  is  Stroke
Test data  219  is  Stroke
Test data  220  is  normal
Test data  221  is  Stroke
Test data  222  is  normal
Test data  223  is  Stroke
Test data  224  is  Stroke
Test data  225  is  Stroke
Test data  226  is  normal
Test data  227  is  Stroke
Test data  228  is  Stroke
Test data  229  is  normal
Test data  230  is  normal
Test data  231  is  Stroke
Test data  232  is  normal
Test data  233  is  Stroke
Test data  234  is  Stroke
Test data  235  is  Stroke
Test data  236  is  Stroke
Test data  237  is  Stroke
Test data  238  is  Stroke
Test data  239  is  Stroke
Test data  240  is  Stroke
Test data  241  is  normal
Test data  242  is  Stroke
Test data  243  is  Stroke
Test data  244  is  Stroke
Test data  245  is  normal
Test data  246  is  Stroke
Test data  247  is  Stroke
Test data  248  is  Stroke
Test data  249  is  Stroke
Test data  250  is  Stroke
Test data  251  is  normal
Test data  252  is  Stroke
Test data  253  is  Stroke
Test data  254  is  Stroke
Test data  255  is  Stroke
Test data  256  is  Stroke
Test data  257  is  Stroke
Test data  258  is  Stroke
Test data  259  is  normal
Test data  260  is  Stroke
Test data  261  is  Stroke
Test data  262  is  Stroke
Test data  263  is  Stroke
Test data  264  is  Stroke
Test data  265  is  normal
Test data  266  is  normal
Test data  267  is  Stroke
Test data  268  is  normal
Test data  269  is  Stroke
Test data  270  is  Stroke
Test data  271  is  Stroke
Test data  272  is  Stroke
Test data  273  is  Stroke
Test data  274  is  Stroke
Test data  275  is  Stroke
Test data  276  is  Stroke
Test data  277  is  Stroke
Test data  278  is  Stroke
Test data  279  is  Stroke
Test data  280  is  Stroke
Test data  281  is  Stroke
Test data  282  is  Stroke
Test data  283  is  Stroke
Test data  284  is  Stroke
Test data  285  is  Stroke
Test data  286  is  Stroke
Test data  287  is  normal
Test data  288  is  Stroke
Test data  289  is  normal
Test data  290  is  Stroke
Test data  291  is  Stroke
Test data  292  is  Stroke
Test data  293  is  normal
Test data  294  is  Stroke
Test data  295  is  Stroke
Test data  296  is  Stroke
Test data  297  is  Stroke
Test data  298  is  normal
Test data  299  is  Stroke
Test data  300  is  normal
Test data  301  is  Stroke
Test data  302  is  normal
Test data  303  is  Stroke
Test data  304  is  Stroke
Test data  305  is  Stroke
Test data  306  is  Stroke
Test data  307  is  normal
Test data  308  is  Stroke
Test data  309  is  Stroke
Test data  310  is  Stroke
Test data  311  is  Stroke
Test data  312  is  Stroke
Test data  313  is  Stroke
Test data  314  is  Stroke
Test data  315  is  Stroke
Test data  316  is  normal
Test data  317  is  Stroke
Test data  318  is  Stroke
Test data  319  is  Stroke
Test data  320  is  Stroke
Test data  321  is  Stroke
Test data  322  is  Stroke
Test data  323  is  Stroke
Test data  324  is  normal
Test data  325  is  Stroke
Test data  326  is  Stroke
Test data  327  is  Stroke
Test data  328  is  Stroke
Test data  329  is  Stroke
Test data  330  is  Stroke
Test data  331  is  Stroke
Test data  332  is  Stroke
Test data  333  is  Stroke
Test data  334  is  Stroke
Test data  335  is  Stroke
Test data  336  is  Stroke
Test data  337  is  Stroke
Test data  338  is  Stroke
Test data  339  is  Stroke
Test data  340  is  normal
Test data  341  is  Stroke
Test data  342  is  Stroke
Test data  343  is  Stroke
Test data  344  is  Stroke
Test data  345  is  Stroke
Test data  346  is  normal
Test data  347  is  Stroke
Test data  348  is  Stroke
Test data  349  is  Stroke
Test data  350  is  Stroke
Test data  351  is  Stroke
Test data  352  is  Stroke
Test data  353  is  Stroke
Test data  354  is  Stroke
Test data  355  is  Stroke
Test data  356  is  Stroke
Test data  357  is  Stroke
Test data  358  is  Stroke
Test data  359  is  Stroke
Test data  360  is  Stroke
Test data  361  is  Stroke
Test data  362  is  Stroke
Test data  363  is  normal
Test data  364  is  Stroke
Test data  365  is  normal
Test data  366  is  Stroke
Test data  367  is  Stroke
Test data  368  is  Stroke
Test data  369  is  Stroke
Test data  370  is  Stroke
Test data  371  is  normal
Test data  372  is  Stroke
Test data  373  is  normal
Test data  374  is  Stroke
Test data  375  is  Stroke
Test data  376  is  Stroke
Test data  377  is  Stroke
Test data  378  is  Stroke
Test data  379  is  Stroke
Test data  380  is  Stroke
Test data  381  is  Stroke
Test data  382  is  Stroke
Test data  383  is  normal
Test data  384  is  normal
Test data  385  is  Stroke
Test data  386  is  Stroke
Test data  387  is  normal
Test data  388  is  normal
Test data  389  is  normal
Test data  390  is  Stroke
Test data  391  is  Stroke
Test data  392  is  normal
Test data  393  is  Stroke
Test data  394  is  Stroke
Test data  395  is  normal
Test data  396  is  Stroke
Test data  397  is  Stroke
Test data  398  is  Stroke
Test data  399  is  Stroke
Test data  400  is  Stroke
Test data  401  is  Stroke
Test data  402  is  normal
Test data  403  is  normal
Test data  404  is  normal
Test data  405  is  Stroke
Test data  406  is  Stroke
Test data  407  is  Stroke
Test data  408  is  normal
Test data  409  is  Stroke
Test data  410  is  Stroke
Test data  411  is  Stroke
Test data  412  is  Stroke
Test data  413  is  Stroke
Test data  414  is  Stroke
Test data  415  is  normal
Test data  416  is  Stroke
Test data  417  is  Stroke
Test data  418  is  Stroke
Test data  419  is  normal
Test data  420  is  Stroke
Test data  421  is  Stroke
Test data  422  is  Stroke
Test data  423  is  Stroke
Test data  424  is  Stroke
Test data  425  is  Stroke
Test data  426  is  normal
Test data  427  is  Stroke
Test data  428  is  Stroke
Test data  429  is  Stroke
Test data  430  is  normal
Test data  431  is  Stroke
Test data  432  is  normal
Test data  433  is  Stroke
Test data  434  is  normal
Test data  435  is  Stroke
Test data  436  is  Stroke
Test data  437  is  normal
Test data  438  is  Stroke
Test data  439  is  Stroke
Test data  440  is  Stroke
Test data  441  is  Stroke
Test data  442  is  normal
Test data  443  is  Stroke
Test data  444  is  Stroke
Test data  445  is  Stroke
Test data  446  is  Stroke
Test data  447  is  normal
Test data  448  is  normal
Test data  449  is  normal
Test data  450  is  Stroke
Test data  451  is  normal
Test data  452  is  normal
Test data  453  is  Stroke
Test data  454  is  Stroke
Test data  455  is  Stroke
Test data  456  is  Stroke
Test data  457  is  Stroke
Test data  458  is  Stroke
Test data  459  is  normal
Test data  460  is  Stroke
Test data  461  is  normal
Test data  462  is  Stroke
Test data  463  is  Stroke
Test data  464  is  normal
Test data  465  is  Stroke
Test data  466  is  Stroke
Test data  467  is  Stroke
Test data  468  is  Stroke
Test data  469  is  normal
Test data  470  is  Stroke
Test data  471  is  Stroke
Test data  472  is  Stroke
Test data  473  is  normal
Test data  474  is  Stroke
Test data  475  is  Stroke
Test data  476  is  Stroke
Test data  477  is  Stroke
Test data  478  is  Stroke
Test data  479  is  normal
Test data  480  is  Stroke
Test data  481  is  Stroke
Test data  482  is  Stroke
Test data  483  is  Stroke
Test data  484  is  Stroke
Test data  485  is  Stroke
Test data  486  is  Stroke
Test data  487  is  Stroke
Test data  488  is  Stroke
Test data  489  is  Stroke
Test data  490  is  normal
Test data  491  is  normal
Test data  492  is  normal
Test data  493  is  Stroke
Test data  494  is  normal
Test data  495  is  normal
Test data  496  is  Stroke
Test data  497  is  Stroke
Test data  498  is  Stroke
Test data  499  is  Stroke
Test data  500  is  Stroke
Test data  501  is  normal
Test data  502  is  Stroke
Test data  503  is  Stroke
Test data  504  is  normal
Test data  505  is  Stroke
Test data  506  is  normal
Test data  507  is  normal
Test data  508  is  normal
Test data  509  is  normal
Test data  510  is  normal
Test data  511  is  Stroke
Test data  512  is  Stroke
Test data  513  is  Stroke
Test data  514  is  Stroke
Test data  515  is  Stroke
Test data  516  is  normal
Test data  517  is  Stroke
Test data  518  is  Stroke
Test data  519  is  Stroke
Test data  520  is  Stroke
Test data  521  is  Stroke
Test data  522  is  Stroke
Test data  523  is  Stroke
Test data  524  is  Stroke
Test data  525  is  Stroke
Test data  526  is  normal
Test data  527  is  normal
Test data  528  is  Stroke
Test data  529  is  Stroke
Test data  530  is  Stroke
Test data  531  is  normal
Test data  532  is  Stroke
Test data  533  is  normal
Test data  534  is  Stroke
Test data  535  is  normal
Test data  536  is  normal
Test data  537  is  normal
Test data  538  is  Stroke
Test data  539  is  Stroke
Test data  540  is  Stroke
Test data  541  is  Stroke
Test data  542  is  Stroke
Test data  543  is  Stroke
Test data  544  is  Stroke
Test data  545  is  Stroke
Test data  546  is  Stroke
Test data  547  is  Stroke
Test data  548  is  Stroke
Test data  549  is  Stroke
Test data  550  is  normal
Test data  551  is  normal
Test data  552  is  Stroke
Test data  553  is  Stroke
Test data  554  is  normal
Test data  555  is  normal
Test data  556  is  Stroke
Test data  557  is  Stroke
Test data  558  is  Stroke
Test data  559  is  Stroke
Test data  560  is  normal
Test data  561  is  normal
Test data  562  is  normal
Test data  563  is  Stroke
Test data  564  is  normal
Test data  565  is  Stroke
Test data  566  is  normal
Test data  567  is  normal
Test data  568  is  normal
Test data  569  is  Stroke
Test data  570  is  Stroke
Test data  571  is  Stroke
Test data  572  is  Stroke
Test data  573  is  Stroke
Test data  574  is  normal
Test data  575  is  normal
Test data  576  is  Stroke
Test data  577  is  Stroke
Test data  578  is  normal
Test data  579  is  normal
Test data  580  is  normal
Test data  581  is  normal
Test data  582  is  Stroke
Test data  583  is  normal
Test data  584  is  normal
Test data  585  is  Stroke
Test data  586  is  Stroke
Test data  587  is  normal
Test data  588  is  Stroke
Test data  589  is  Stroke
Test data  590  is  Stroke
Test data  591  is  Stroke
Test data  592  is  Stroke
Test data  593  is  normal
Test data  594  is  Stroke
Test data  595  is  Stroke
Test data  596  is  Stroke
Test data  597  is  normal
Test data  598  is  Stroke
Test data  599  is  normal
Test data  600  is  Stroke
Test data  601  is  Stroke
Test data  602  is  Stroke
Test data  603  is  normal
Test data  604  is  normal
Test data  605  is  Stroke
Test data  606  is  Stroke
Test data  607  is  Stroke
Test data  608  is  normal
Test data  609  is  Stroke
Test data  610  is  Stroke
Test data  611  is  Stroke
Test data  612  is  Stroke
Test data  613  is  Stroke
Test data  614  is  Stroke
Test data  615  is  Stroke
Test data  616  is  Stroke
Test data  617  is  normal
Test data  618  is  normal
Test data  619  is  normal
Test data  620  is  Stroke
Test data  621  is  normal
Test data  622  is  normal
Test data  623  is  Stroke
Test data  624  is  Stroke
Test data  625  is  Stroke
Test data  626  is  Stroke
Test data  627  is  normal
Test data  628  is  Stroke
Test data  629  is  Stroke
Test data  630  is  Stroke
Test data  631  is  Stroke
Test data  632  is  Stroke
Test data  633  is  normal
Test data  634  is  Stroke
Test data  635  is  Stroke
Test data  636  is  normal
Test data  637  is  Stroke
Test data  638  is  Stroke
Test data  639  is  Stroke
Test data  640  is  normal
Test data  641  is  Stroke
Test data  642  is  Stroke
Test data  643  is  Stroke
Test data  644  is  Stroke
Test data  645  is  normal
Test data  646  is  Stroke
Test data  647  is  normal
Test data  648  is  Stroke
Test data  649  is  Stroke
Test data  650  is  normal
Test data  651  is  Stroke
Test data  652  is  Stroke
Test data  653  is  Stroke
Test data  654  is  Stroke
Test data  655  is  Stroke
Test data  656  is  Stroke
Test data  657  is  Stroke
Test data  658  is  Stroke
Test data  659  is  Stroke
Test data  660  is  Stroke
Test data  661  is  Stroke
Test data  662  is  normal
Test data  663  is  Stroke
Test data  664  is  Stroke
Test data  665  is  Stroke
Test data  666  is  normal
Test data  667  is  Stroke
Test data  668  is  Stroke
Test data  669  is  Stroke
Test data  670  is  normal
Test data  671  is  Stroke
Test data  672  is  Stroke
Test data  673  is  Stroke
Test data  674  is  Stroke
Test data  675  is  Stroke
Test data  676  is  Stroke
Test data  677  is  normal
Test data  678  is  Stroke
Test data  679  is  Stroke
Test data  680  is  Stroke
Test data  681  is  Stroke
Test data  682  is  Stroke
Test data  683  is  Stroke
Test data  684  is  Stroke
Test data  685  is  normal
Test data  686  is  Stroke
Test data  687  is  Stroke
Test data  688  is  Stroke
Test data  689  is  Stroke
Test data  690  is  Stroke
Test data  691  is  Stroke
Test data  692  is  Stroke
Test data  693  is  Stroke
Test data  694  is  Stroke
Test data  695  is  Stroke
Test data  696  is  Stroke
Test data  697  is  Stroke
Test data  698  is  Stroke
Test data  699  is  Stroke
Test data  700  is  Stroke
Test data  701  is  Stroke
Test data  702  is  Stroke
Test data  703  is  Stroke
Test data  704  is  normal
Test data  705  is  normal
Test data  706  is  Stroke
Test data  707  is  Stroke
Test data  708  is  Stroke
Test data  709  is  normal
Test data  710  is  Stroke
Test data  711  is  normal
Test data  712  is  Stroke
Test data  713  is  Stroke
Test data  714  is  Stroke
Test data  715  is  Stroke
Test data  716  is  normal
Test data  717  is  Stroke
Test data  718  is  Stroke
Test data  719  is  Stroke
Test data  720  is  Stroke
Test data  721  is  Stroke
Test data  722  is  Stroke
Test data  723  is  Stroke
Test data  724  is  normal
Test data  725  is  normal
Test data  726  is  Stroke
Test data  727  is  Stroke
Test data  728  is  Stroke
Test data  729  is  Stroke
Test data  730  is  Stroke
Test data  731  is  Stroke
Test data  732  is  Stroke
Test data  733  is  Stroke
Test data  734  is  Stroke
Test data  735  is  Stroke
Test data  736  is  Stroke
Test data  737  is  Stroke
Test data  738  is  Stroke
Test data  739  is  Stroke
Test data  740  is  Stroke
Test data  741  is  normal
Test data  742  is  Stroke
Test data  743  is  Stroke

In [111]:
print(confusion_matrix(y_test,y_pred))

[[ 354  246]
 [  97 1053]]

In [112]:
print("Accuracy for Logistic Regression : {}%".format(metrics.accuracy_score(y_test, y_pred)*100))

Accuracy for Logistic Regression : 80.4%

In [113]:
from sklearn.neighbors import KNeighborsClassifier

In [114]:
knn = KNeighborsClassifier(n_neighbors=7)
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=7)

In [115]:
y_pred = knn.predict(X_test)
for i in range(0, len(y_pred)):
    i2=str(i)
    res=''
    if y_pred[i]==0:
        res='normal'
    elif y_pred[i]==1:
        res='Stroke'
    print('Test data ',i2 , ' is ',res)

Test data  0  is  Stroke
Test data  1  is  Stroke
Test data  2  is  Stroke
Test data  3  is  Stroke
Test data  4  is  Stroke
Test data  5  is  Stroke
Test data  6  is  Stroke
Test data  7  is  Stroke
Test data  8  is  Stroke
Test data  9  is  Stroke
Test data  10  is  Stroke
Test data  11  is  Stroke
Test data  12  is  Stroke
Test data  13  is  Stroke
Test data  14  is  Stroke
Test data  15  is  Stroke
Test data  16  is  normal
Test data  17  is  Stroke
Test data  18  is  Stroke
Test data  19  is  Stroke
Test data  20  is  Stroke
Test data  21  is  Stroke
Test data  22  is  Stroke
Test data  23  is  Stroke
Test data  24  is  Stroke
Test data  25  is  Stroke
Test data  26  is  Stroke
Test data  27  is  Stroke
Test data  28  is  Stroke
Test data  29  is  Stroke
Test data  30  is  normal
Test data  31  is  Stroke
Test data  32  is  Stroke
Test data  33  is  Stroke
Test data  34  is  Stroke
Test data  35  is  normal
Test data  36  is  Stroke
Test data  37  is  Stroke
Test data  38  is  Stroke
Test data  39  is  Stroke
Test data  40  is  Stroke
Test data  41  is  Stroke
Test data  42  is  Stroke
Test data  43  is  normal
Test data  44  is  normal
Test data  45  is  Stroke
Test data  46  is  normal
Test data  47  is  Stroke
Test data  48  is  normal
Test data  49  is  Stroke
Test data  50  is  Stroke
Test data  51  is  Stroke
Test data  52  is  Stroke
Test data  53  is  Stroke
Test data  54  is  normal
Test data  55  is  Stroke
Test data  56  is  Stroke
Test data  57  is  Stroke
Test data  58  is  Stroke
Test data  59  is  Stroke
Test data  60  is  Stroke
Test data  61  is  Stroke
Test data  62  is  Stroke
Test data  63  is  Stroke
Test data  64  is  Stroke
Test data  65  is  Stroke
Test data  66  is  Stroke
Test data  67  is  Stroke
Test data  68  is  Stroke
Test data  69  is  Stroke
Test data  70  is  normal
Test data  71  is  Stroke
Test data  72  is  Stroke
Test data  73  is  Stroke
Test data  74  is  Stroke
Test data  75  is  Stroke
Test data  76  is  normal
Test data  77  is  Stroke
Test data  78  is  Stroke
Test data  79  is  Stroke
Test data  80  is  Stroke
Test data  81  is  Stroke
Test data  82  is  Stroke
Test data  83  is  Stroke
Test data  84  is  Stroke
Test data  85  is  Stroke
Test data  86  is  Stroke
Test data  87  is  Stroke
Test data  88  is  normal
Test data  89  is  Stroke
Test data  90  is  Stroke
Test data  91  is  normal
Test data  92  is  Stroke
Test data  93  is  normal
Test data  94  is  Stroke
Test data  95  is  Stroke
Test data  96  is  Stroke
Test data  97  is  Stroke
Test data  98  is  normal
Test data  99  is  Stroke
Test data  100  is  Stroke
Test data  101  is  normal
Test data  102  is  normal
Test data  103  is  Stroke
Test data  104  is  normal
Test data  105  is  Stroke
Test data  106  is  Stroke
Test data  107  is  Stroke
Test data  108  is  Stroke
Test data  109  is  Stroke
Test data  110  is  Stroke
Test data  111  is  Stroke
Test data  112  is  normal
Test data  113  is  Stroke
Test data  114  is  Stroke
Test data  115  is  Stroke
Test data  116  is  Stroke
Test data  117  is  Stroke
Test data  118  is  normal
Test data  119  is  Stroke
Test data  120  is  Stroke
Test data  121  is  Stroke
Test data  122  is  Stroke
Test data  123  is  Stroke
Test data  124  is  Stroke
Test data  125  is  Stroke
Test data  126  is  Stroke
Test data  127  is  Stroke
Test data  128  is  normal
Test data  129  is  normal
Test data  130  is  normal
Test data  131  is  Stroke
Test data  132  is  Stroke
Test data  133  is  normal
Test data  134  is  normal
Test data  135  is  Stroke
Test data  136  is  Stroke
Test data  137  is  Stroke
Test data  138  is  Stroke
Test data  139  is  Stroke
Test data  140  is  normal
Test data  141  is  normal
Test data  142  is  Stroke
Test data  143  is  Stroke
Test data  144  is  normal
Test data  145  is  Stroke
Test data  146  is  Stroke
Test data  147  is  Stroke
Test data  148  is  Stroke
Test data  149  is  Stroke
Test data  150  is  Stroke
Test data  151  is  Stroke
Test data  152  is  normal
Test data  153  is  Stroke
Test data  154  is  normal
Test data  155  is  Stroke
Test data  156  is  Stroke
Test data  157  is  Stroke
Test data  158  is  Stroke
Test data  159  is  Stroke
Test data  160  is  Stroke
Test data  161  is  normal
Test data  162  is  Stroke
Test data  163  is  Stroke
Test data  164  is  Stroke
Test data  165  is  Stroke
Test data  166  is  Stroke
Test data  167  is  Stroke
Test data  168  is  Stroke
Test data  169  is  Stroke
Test data  170  is  normal
Test data  171  is  normal
Test data  172  is  Stroke
Test data  173  is  normal
Test data  174  is  Stroke
Test data  175  is  Stroke
Test data  176  is  Stroke
Test data  177  is  normal
Test data  178  is  Stroke
Test data  179  is  Stroke
Test data  180  is  Stroke
Test data  181  is  Stroke
Test data  182  is  normal
Test data  183  is  normal
Test data  184  is  Stroke
Test data  185  is  Stroke
Test data  186  is  Stroke
Test data  187  is  Stroke
Test data  188  is  Stroke
Test data  189  is  Stroke
Test data  190  is  Stroke
Test data  191  is  Stroke
Test data  192  is  normal
Test data  193  is  normal
Test data  194  is  Stroke
Test data  195  is  Stroke
Test data  196  is  Stroke
Test data  197  is  normal
Test data  198  is  Stroke
Test data  199  is  Stroke
Test data  200  is  Stroke
Test data  201  is  normal
Test data  202  is  Stroke
Test data  203  is  Stroke
Test data  204  is  Stroke
Test data  205  is  Stroke
Test data  206  is  Stroke
Test data  207  is  normal
Test data  208  is  Stroke
Test data  209  is  Stroke
Test data  210  is  Stroke
Test data  211  is  Stroke
Test data  212  is  normal
Test data  213  is  Stroke
Test data  214  is  normal
Test data  215  is  normal
Test data  216  is  Stroke
Test data  217  is  normal
Test data  218  is  Stroke
Test data  219  is  Stroke
Test data  220  is  normal
Test data  221  is  Stroke
Test data  222  is  normal
Test data  223  is  Stroke
Test data  224  is  Stroke
Test data  225  is  Stroke
Test data  226  is  normal
Test data  227  is  Stroke
Test data  228  is  Stroke
Test data  229  is  normal
Test data  230  is  normal
Test data  231  is  Stroke
Test data  232  is  normal
Test data  233  is  normal
Test data  234  is  Stroke
Test data  235  is  Stroke
Test data  236  is  Stroke
Test data  237  is  Stroke
Test data  238  is  Stroke
Test data  239  is  Stroke
Test data  240  is  Stroke
Test data  241  is  Stroke
Test data  242  is  Stroke
Test data  243  is  Stroke
Test data  244  is  Stroke
Test data  245  is  normal
Test data  246  is  Stroke
Test data  247  is  Stroke
Test data  248  is  Stroke
Test data  249  is  Stroke
Test data  250  is  Stroke
Test data  251  is  normal
Test data  252  is  Stroke
Test data  253  is  Stroke
Test data  254  is  Stroke
Test data  255  is  Stroke
Test data  256  is  Stroke
Test data  257  is  Stroke
Test data  258  is  normal
Test data  259  is  normal
Test data  260  is  Stroke
Test data  261  is  Stroke
Test data  262  is  Stroke
Test data  263  is  Stroke
Test data  264  is  Stroke
Test data  265  is  normal
Test data  266  is  Stroke
Test data  267  is  Stroke
Test data  268  is  Stroke
Test data  269  is  Stroke
Test data  270  is  Stroke
Test data  271  is  normal
Test data  272  is  Stroke
Test data  273  is  Stroke
Test data  274  is  Stroke
Test data  275  is  Stroke
Test data  276  is  Stroke
Test data  277  is  normal
Test data  278  is  Stroke
Test data  279  is  Stroke
Test data  280  is  Stroke
Test data  281  is  Stroke
Test data  282  is  Stroke
Test data  283  is  Stroke
Test data  284  is  Stroke
Test data  285  is  Stroke
Test data  286  is  Stroke
Test data  287  is  Stroke
Test data  288  is  Stroke
Test data  289  is  Stroke
Test data  290  is  Stroke
Test data  291  is  Stroke
Test data  292  is  normal
Test data  293  is  Stroke
Test data  294  is  Stroke
Test data  295  is  Stroke
Test data  296  is  Stroke
Test data  297  is  Stroke
Test data  298  is  normal
Test data  299  is  Stroke
Test data  300  is  normal
Test data  301  is  Stroke
Test data  302  is  Stroke
Test data  303  is  normal
Test data  304  is  Stroke
Test data  305  is  Stroke
Test data  306  is  Stroke
Test data  307  is  normal
Test data  308  is  Stroke
Test data  309  is  Stroke
Test data  310  is  Stroke
Test data  311  is  Stroke
Test data  312  is  Stroke
Test data  313  is  Stroke
Test data  314  is  Stroke
Test data  315  is  Stroke
Test data  316  is  Stroke
Test data  317  is  Stroke
Test data  318  is  Stroke
Test data  319  is  Stroke
Test data  320  is  Stroke
Test data  321  is  Stroke
Test data  322  is  Stroke
Test data  323  is  normal
Test data  324  is  Stroke
Test data  325  is  Stroke
Test data  326  is  Stroke
Test data  327  is  Stroke
Test data  328  is  normal
Test data  329  is  Stroke
Test data  330  is  normal
Test data  331  is  Stroke
Test data  332  is  normal
Test data  333  is  Stroke
Test data  334  is  Stroke
Test data  335  is  Stroke
Test data  336  is  Stroke
Test data  337  is  Stroke
Test data  338  is  Stroke
Test data  339  is  normal
Test data  340  is  Stroke
Test data  341  is  Stroke
Test data  342  is  Stroke
Test data  343  is  Stroke
Test data  344  is  normal
Test data  345  is  Stroke
Test data  346  is  Stroke
Test data  347  is  Stroke
Test data  348  is  Stroke
Test data  349  is  Stroke
Test data  350  is  Stroke
Test data  351  is  Stroke
Test data  352  is  Stroke
Test data  353  is  Stroke
Test data  354  is  Stroke
Test data  355  is  Stroke
Test data  356  is  Stroke
Test data  357  is  normal
Test data  358  is  Stroke
Test data  359  is  Stroke
Test data  360  is  Stroke
Test data  361  is  Stroke
Test data  362  is  normal
Test data  363  is  Stroke
Test data  364  is  Stroke
Test data  365  is  Stroke
Test data  366  is  Stroke
Test data  367  is  Stroke
Test data  368  is  Stroke
Test data  369  is  Stroke
Test data  370  is  normal
Test data  371  is  normal
Test data  372  is  Stroke
Test data  373  is  normal
Test data  374  is  normal
Test data  375  is  Stroke
Test data  376  is  Stroke
Test data  377  is  normal
Test data  378  is  Stroke
Test data  379  is  Stroke
Test data  380  is  Stroke
Test data  381  is  Stroke
Test data  382  is  Stroke
Test data  383  is  Stroke
Test data  384  is  normal
Test data  385  is  Stroke
Test data  386  is  Stroke
Test data  387  is  Stroke
Test data  388  is  Stroke
Test data  389  is  normal
Test data  390  is  Stroke
Test data  391  is  Stroke
Test data  392  is  normal
Test data  393  is  Stroke
Test data  394  is  Stroke
Test data  395  is  normal
Test data  396  is  Stroke
Test data  397  is  Stroke
Test data  398  is  Stroke
Test data  399  is  Stroke
Test data  400  is  normal
Test data  401  is  Stroke
Test data  402  is  Stroke
Test data  403  is  Stroke
Test data  404  is  normal
Test data  405  is  normal
Test data  406  is  normal
Test data  407  is  Stroke
Test data  408  is  normal
Test data  409  is  normal
Test data  410  is  Stroke
Test data  411  is  Stroke
Test data  412  is  Stroke
Test data  413  is  Stroke
Test data  414  is  Stroke
Test data  415  is  normal
Test data  416  is  Stroke
Test data  417  is  Stroke
Test data  418  is  Stroke
Test data  419  is  Stroke
Test data  420  is  Stroke
Test data  421  is  Stroke
Test data  422  is  Stroke
Test data  423  is  Stroke
Test data  424  is  Stroke
Test data  425  is  Stroke
Test data  426  is  Stroke
Test data  427  is  Stroke
Test data  428  is  Stroke
Test data  429  is  Stroke
Test data  430  is  normal
Test data  431  is  Stroke
Test data  432  is  normal
Test data  433  is  Stroke
Test data  434  is  Stroke
Test data  435  is  Stroke
Test data  436  is  Stroke
Test data  437  is  normal
Test data  438  is  Stroke
Test data  439  is  Stroke
Test data  440  is  Stroke
Test data  441  is  Stroke
Test data  442  is  Stroke
Test data  443  is  Stroke
Test data  444  is  Stroke
Test data  445  is  Stroke
Test data  446  is  Stroke
Test data  447  is  normal
Test data  448  is  normal
Test data  449  is  Stroke
Test data  450  is  Stroke
Test data  451  is  Stroke
Test data  452  is  normal
Test data  453  is  Stroke
Test data  454  is  Stroke
Test data  455  is  Stroke
Test data  456  is  Stroke
Test data  457  is  Stroke
Test data  458  is  Stroke
Test data  459  is  Stroke
Test data  460  is  Stroke
Test data  461  is  Stroke
Test data  462  is  Stroke
Test data  463  is  Stroke
Test data  464  is  Stroke
Test data  465  is  Stroke
Test data  466  is  Stroke
Test data  467  is  Stroke
Test data  468  is  Stroke
Test data  469  is  Stroke
Test data  470  is  Stroke
Test data  471  is  Stroke
Test data  472  is  Stroke
Test data  473  is  normal
Test data  474  is  Stroke
Test data  475  is  normal
Test data  476  is  normal
Test data  477  is  Stroke
Test data  478  is  Stroke
Test data  479  is  normal
Test data  480  is  Stroke
Test data  481  is  Stroke
Test data  482  is  Stroke
Test data  483  is  Stroke
Test data  484  is  Stroke
Test data  485  is  Stroke
Test data  486  is  Stroke
Test data  487  is  Stroke
Test data  488  is  Stroke
Test data  489  is  Stroke
Test data  490  is  Stroke
Test data  491  is  normal
Test data  492  is  Stroke
Test data  493  is  Stroke
Test data  494  is  normal
Test data  495  is  normal
Test data  496  is  Stroke
Test data  497  is  Stroke
Test data  498  is  Stroke
Test data  499  is  Stroke
Test data  500  is  Stroke
Test data  501  is  Stroke
Test data  502  is  Stroke
Test data  503  is  Stroke
Test data  504  is  normal
Test data  505  is  Stroke
Test data  506  is  normal
Test data  507  is  normal
Test data  508  is  normal
Test data  509  is  Stroke
Test data  510  is  Stroke
Test data  511  is  Stroke
Test data  512  is  Stroke
Test data  513  is  Stroke
Test data  514  is  normal
Test data  515  is  Stroke
Test data  516  is  normal
Test data  517  is  Stroke
Test data  518  is  Stroke
Test data  519  is  Stroke
Test data  520  is  normal
Test data  521  is  Stroke
Test data  522  is  Stroke
Test data  523  is  Stroke
Test data  524  is  Stroke
Test data  525  is  normal
Test data  526  is  Stroke
Test data  527  is  Stroke
Test data  528  is  Stroke
Test data  529  is  Stroke
Test data  530  is  Stroke
Test data  531  is  Stroke
Test data  532  is  normal
Test data  533  is  Stroke
Test data  534  is  Stroke
Test data  535  is  normal
Test data  536  is  Stroke
Test data  537  is  normal
Test data  538  is  normal
Test data  539  is  Stroke
Test data  540  is  Stroke
Test data  541  is  Stroke
Test data  542  is  Stroke
Test data  543  is  Stroke
Test data  544  is  Stroke
Test data  545  is  Stroke
Test data  546  is  normal
Test data  547  is  Stroke
Test data  548  is  Stroke
Test data  549  is  Stroke
Test data  550  is  Stroke
Test data  551  is  Stroke
Test data  552  is  Stroke
Test data  553  is  Stroke
Test data  554  is  Stroke
Test data  555  is  Stroke
Test data  556  is  Stroke
Test data  557  is  Stroke
Test data  558  is  Stroke
Test data  559  is  Stroke
Test data  560  is  normal
Test data  561  is  normal
Test data  562  is  Stroke
Test data  563  is  Stroke
Test data  564  is  Stroke
Test data  565  is  Stroke
Test data  566  is  normal
Test data  567  is  Stroke
Test data  568  is  Stroke
Test data  569  is  Stroke
Test data  570  is  Stroke
Test data  571  is  Stroke
Test data  572  is  Stroke
Test data  573  is  Stroke
Test data  574  is  Stroke
Test data  575  is  normal
Test data  576  is  Stroke
Test data  577  is  Stroke
Test data  578  is  Stroke
Test data  579  is  normal
Test data  580  is  Stroke
Test data  581  is  Stroke
Test data  582  is  Stroke
Test data  583  is  Stroke
Test data  584  is  Stroke
Test data  585  is  Stroke
Test data  586  is  Stroke
Test data  587  is  normal
Test data  588  is  normal
Test data  589  is  Stroke
Test data  590  is  Stroke
Test data  591  is  Stroke
Test data  592  is  Stroke
Test data  593  is  Stroke
Test data  594  is  Stroke
Test data  595  is  Stroke
Test data  596  is  Stroke
Test data  597  is  normal
Test data  598  is  Stroke
Test data  599  is  Stroke
Test data  600  is  normal
Test data  601  is  Stroke
Test data  602  is  normal
Test data  603  is  Stroke
Test data  604  is  normal
Test data  605  is  Stroke
Test data  606  is  Stroke
Test data  607  is  normal
Test data  608  is  Stroke
Test data  609  is  Stroke
Test data  610  is  Stroke
Test data  611  is  Stroke
Test data  612  is  Stroke
Test data  613  is  Stroke
Test data  614  is  Stroke
Test data  615  is  Stroke
Test data  616  is  Stroke
Test data  617  is  normal
Test data  618  is  normal
Test data  619  is  Stroke
Test data  620  is  Stroke
Test data  621  is  normal
Test data  622  is  Stroke
Test data  623  is  Stroke
Test data  624  is  Stroke
Test data  625  is  Stroke
Test data  626  is  Stroke
Test data  627  is  normal
Test data  628  is  Stroke
Test data  629  is  Stroke
Test data  630  is  Stroke
Test data  631  is  Stroke
Test data  632  is  Stroke
Test data  633  is  Stroke
Test data  634  is  Stroke
Test data  635  is  Stroke
Test data  636  is  Stroke
Test data  637  is  Stroke
Test data  638  is  Stroke
Test data  639  is  Stroke
Test data  640  is  Stroke
Test data  641  is  Stroke
Test data  642  is  Stroke
Test data  643  is  Stroke
Test data  644  is  Stroke
Test data  645  is  normal
Test data  646  is  Stroke
Test data  647  is  Stroke
Test data  648  is  Stroke
Test data  649  is  Stroke
Test data  650  is  Stroke
Test data  651  is  Stroke
Test data  652  is  Stroke
Test data  653  is  Stroke
Test data  654  is  Stroke
Test data  655  is  Stroke
Test data  656  is  Stroke
Test data  657  is  Stroke
Test data  658  is  Stroke
Test data  659  is  Stroke
Test data  660  is  Stroke
Test data  661  is  Stroke
Test data  662  is  normal
Test data  663  is  Stroke
Test data  664  is  Stroke
Test data  665  is  Stroke
Test data  666  is  Stroke
Test data  667  is  normal
Test data  668  is  Stroke
Test data  669  is  Stroke
Test data  670  is  Stroke
Test data  671  is  Stroke
Test data  672  is  Stroke
Test data  673  is  Stroke
Test data  674  is  Stroke
Test data  675  is  Stroke
Test data  676  is  Stroke
Test data  677  is  normal
Test data  678  is  Stroke
Test data  679  is  Stroke
Test data  680  is  Stroke
Test data  681  is  Stroke
Test data  682  is  Stroke
Test data  683  is  Stroke
Test data  684  is  Stroke
Test data  685  is  Stroke
Test data  686  is  Stroke
Test data  687  is  Stroke
Test data  688  is  Stroke
Test data  689  is  Stroke
Test data  690  is  Stroke
Test data  691  is  Stroke
Test data  692  is  Stroke
Test data  693  is  Stroke
Test data  694  is  Stroke
Test data  695  is  normal
Test data  696  is  Stroke
Test data  697  is  Stroke
Test data  698  is  Stroke
Test data  699  is  Stroke
Test data  700  is  Stroke
Test data  701  is  Stroke
Test data  702  is  Stroke
Test data  703  is  Stroke
Test data  704  is  normal
Test data  705  is  Stroke
Test data  706  is  Stroke
Test data  707  is  Stroke
Test data  708  is  Stroke
Test data  709  is  Stroke
Test data  710  is  Stroke
Test data  711  is  normal
Test data  712  is  normal
Test data  713  is  Stroke
Test data  714  is  Stroke
Test data  715  is  normal
Test data  716  is  normal
Test data  717  is  Stroke
Test data  718  is  normal
Test data  719  is  Stroke
Test data  720  is  Stroke
Test data  721  is  Stroke
Test data  722  is  Stroke
Test data  723  is  Stroke
Test data  724  is  normal
Test data  725  is  normal
Test data  726  is  Stroke
Test data  727  is  Stroke
Test data  728  is  Stroke
Test data  729  is  Stroke
Test data  730  is  normal
Test data  731  is  Stroke
Test data  732  is  Stroke
Test data  733  is  Stroke
Test data  734  is  normal
Test data  735  is  Stroke
Test data  736  is  Stroke
Test data  737  is  Stroke
Test data  738  is  Stroke
Test data  739  is  Stroke
Test data  740  is  Stroke
Test data  741  is  normal
Test data  742  is  Stroke
Test data  743  is  Stroke

In [116]:
print(confusion_matrix(y_test,y_pred))

[[ 328  272]
 [  17 1133]]

In [117]:
print("Accuracy for KNN Classifier : {}%".format(metrics.accuracy_score(y_test, y_pred)*100))

Accuracy for KNN Classifier : 83.48571428571428%

In [118]:
SGD = GradientBoostingClassifier(learning_rate=0.1)
SGD.fit(X_train, y_train)

GradientBoostingClassifier()

In [119]:
y_pred = SGD.predict(X_test)
for i in range(0, len(y_pred)):
    i2=str(i)
    res=''
    if y_pred[i]==0:
        res='normal'
    elif y_pred[i]==1:
        res='Stroke'
    print('Test data ',i2 , ' is ',res)

Test data  0  is  normal
Test data  1  is  Stroke
Test data  2  is  Stroke
Test data  3  is  Stroke
Test data  4  is  Stroke
Test data  5  is  Stroke
Test data  6  is  Stroke
Test data  7  is  Stroke
Test data  8  is  Stroke
Test data  9  is  normal
Test data  10  is  Stroke
Test data  11  is  Stroke
Test data  12  is  Stroke
Test data  13  is  Stroke
Test data  14  is  Stroke
Test data  15  is  Stroke
Test data  16  is  normal
Test data  17  is  Stroke
Test data  18  is  Stroke
Test data  19  is  Stroke
Test data  20  is  Stroke
Test data  21  is  Stroke
Test data  22  is  Stroke
Test data  23  is  Stroke
Test data  24  is  Stroke
Test data  25  is  Stroke
Test data  26  is  Stroke
Test data  27  is  Stroke
Test data  28  is  Stroke
Test data  29  is  Stroke
Test data  30  is  normal
Test data  31  is  Stroke
Test data  32  is  Stroke
Test data  33  is  Stroke
Test data  34  is  Stroke
Test data  35  is  normal
Test data  36  is  Stroke
Test data  37  is  Stroke
Test data  38  is  Stroke
Test data  39  is  Stroke
Test data  40  is  Stroke
Test data  41  is  Stroke
Test data  42  is  Stroke
Test data  43  is  normal
Test data  44  is  normal
Test data  45  is  Stroke
Test data  46  is  normal
Test data  47  is  Stroke
Test data  48  is  normal
Test data  49  is  Stroke
Test data  50  is  Stroke
Test data  51  is  Stroke
Test data  52  is  Stroke
Test data  53  is  Stroke
Test data  54  is  normal
Test data  55  is  Stroke
Test data  56  is  Stroke
Test data  57  is  Stroke
Test data  58  is  Stroke
Test data  59  is  Stroke
Test data  60  is  Stroke
Test data  61  is  Stroke
Test data  62  is  Stroke
Test data  63  is  Stroke
Test data  64  is  Stroke
Test data  65  is  Stroke
Test data  66  is  Stroke
Test data  67  is  normal
Test data  68  is  Stroke
Test data  69  is  normal
Test data  70  is  normal
Test data  71  is  Stroke
Test data  72  is  Stroke
Test data  73  is  normal
Test data  74  is  Stroke
Test data  75  is  Stroke
Test data  76  is  Stroke
Test data  77  is  Stroke
Test data  78  is  Stroke
Test data  79  is  normal
Test data  80  is  Stroke
Test data  81  is  Stroke
Test data  82  is  normal
Test data  83  is  Stroke
Test data  84  is  Stroke
Test data  85  is  normal
Test data  86  is  Stroke
Test data  87  is  Stroke
Test data  88  is  normal
Test data  89  is  Stroke
Test data  90  is  Stroke
Test data  91  is  normal
Test data  92  is  Stroke
Test data  93  is  Stroke
Test data  94  is  Stroke
Test data  95  is  Stroke
Test data  96  is  Stroke
Test data  97  is  normal
Test data  98  is  normal
Test data  99  is  Stroke
Test data  100  is  Stroke
Test data  101  is  normal
Test data  102  is  Stroke
Test data  103  is  Stroke
Test data  104  is  Stroke
Test data  105  is  normal
Test data  106  is  Stroke
Test data  107  is  normal
Test data  108  is  Stroke
Test data  109  is  normal
Test data  110  is  Stroke
Test data  111  is  Stroke
Test data  112  is  Stroke
Test data  113  is  Stroke
Test data  114  is  Stroke
Test data  115  is  Stroke
Test data  116  is  Stroke
Test data  117  is  Stroke
Test data  118  is  normal
Test data  119  is  Stroke
Test data  120  is  Stroke
Test data  121  is  Stroke
Test data  122  is  normal
Test data  123  is  normal
Test data  124  is  normal
Test data  125  is  Stroke
Test data  126  is  normal
Test data  127  is  Stroke
Test data  128  is  normal
Test data  129  is  Stroke
Test data  130  is  Stroke
Test data  131  is  normal
Test data  132  is  normal
Test data  133  is  normal
Test data  134  is  Stroke
Test data  135  is  Stroke
Test data  136  is  Stroke
Test data  137  is  Stroke
Test data  138  is  Stroke
Test data  139  is  Stroke
Test data  140  is  Stroke
Test data  141  is  normal
Test data  142  is  Stroke
Test data  143  is  Stroke
Test data  144  is  normal
Test data  145  is  Stroke
Test data  146  is  Stroke
Test data  147  is  normal
Test data  148  is  Stroke
Test data  149  is  normal
Test data  150  is  Stroke
Test data  151  is  Stroke
Test data  152  is  normal
Test data  153  is  Stroke
Test data  154  is  normal
Test data  155  is  normal
Test data  156  is  Stroke
Test data  157  is  Stroke
Test data  158  is  Stroke
Test data  159  is  Stroke
Test data  160  is  normal
Test data  161  is  normal
Test data  162  is  Stroke
Test data  163  is  Stroke
Test data  164  is  Stroke
Test data  165  is  normal
Test data  166  is  Stroke
Test data  167  is  Stroke
Test data  168  is  Stroke
Test data  169  is  Stroke
Test data  170  is  normal
Test data  171  is  Stroke
Test data  172  is  Stroke
Test data  173  is  Stroke
Test data  174  is  Stroke
Test data  175  is  Stroke
Test data  176  is  Stroke
Test data  177  is  normal
Test data  178  is  Stroke
Test data  179  is  normal
Test data  180  is  Stroke
Test data  181  is  Stroke
Test data  182  is  normal
Test data  183  is  normal
Test data  184  is  normal
Test data  185  is  normal
Test data  186  is  normal
Test data  187  is  Stroke
Test data  188  is  Stroke
Test data  189  is  Stroke
Test data  190  is  Stroke
Test data  191  is  Stroke
Test data  192  is  normal
Test data  193  is  normal
Test data  194  is  Stroke
Test data  195  is  Stroke
Test data  196  is  Stroke
Test data  197  is  normal
Test data  198  is  normal
Test data  199  is  Stroke
Test data  200  is  Stroke
Test data  201  is  normal
Test data  202  is  Stroke
Test data  203  is  Stroke
Test data  204  is  Stroke
Test data  205  is  Stroke
Test data  206  is  normal
Test data  207  is  Stroke
Test data  208  is  Stroke
Test data  209  is  Stroke
Test data  210  is  Stroke
Test data  211  is  Stroke
Test data  212  is  Stroke
Test data  213  is  Stroke
Test data  214  is  Stroke
Test data  215  is  normal
Test data  216  is  normal
Test data  217  is  Stroke
Test data  218  is  Stroke
Test data  219  is  Stroke
Test data  220  is  normal
Test data  221  is  Stroke
Test data  222  is  normal
Test data  223  is  Stroke
Test data  224  is  Stroke
Test data  225  is  normal
Test data  226  is  normal
Test data  227  is  Stroke
Test data  228  is  Stroke
Test data  229  is  normal
Test data  230  is  normal
Test data  231  is  Stroke
Test data  232  is  normal
Test data  233  is  Stroke
Test data  234  is  Stroke
Test data  235  is  Stroke
Test data  236  is  Stroke
Test data  237  is  Stroke
Test data  238  is  Stroke
Test data  239  is  Stroke
Test data  240  is  Stroke
Test data  241  is  Stroke
Test data  242  is  Stroke
Test data  243  is  Stroke
Test data  244  is  Stroke
Test data  245  is  normal
Test data  246  is  Stroke
Test data  247  is  Stroke
Test data  248  is  Stroke
Test data  249  is  Stroke
Test data  250  is  Stroke
Test data  251  is  normal
Test data  252  is  Stroke
Test data  253  is  Stroke
Test data  254  is  Stroke
Test data  255  is  Stroke
Test data  256  is  Stroke
Test data  257  is  normal
Test data  258  is  normal
Test data  259  is  normal
Test data  260  is  normal
Test data  261  is  Stroke
Test data  262  is  Stroke
Test data  263  is  Stroke
Test data  264  is  Stroke
Test data  265  is  normal
Test data  266  is  normal
Test data  267  is  Stroke
Test data  268  is  normal
Test data  269  is  normal
Test data  270  is  Stroke
Test data  271  is  Stroke
Test data  272  is  Stroke
Test data  273  is  Stroke
Test data  274  is  Stroke
Test data  275  is  Stroke
Test data  276  is  normal
Test data  277  is  normal
Test data  278  is  Stroke
Test data  279  is  Stroke
Test data  280  is  Stroke
Test data  281  is  Stroke
Test data  282  is  Stroke
Test data  283  is  Stroke
Test data  284  is  Stroke
Test data  285  is  Stroke
Test data  286  is  Stroke
Test data  287  is  Stroke
Test data  288  is  Stroke
Test data  289  is  normal
Test data  290  is  Stroke
Test data  291  is  Stroke
Test data  292  is  Stroke
Test data  293  is  normal
Test data  294  is  Stroke
Test data  295  is  Stroke
Test data  296  is  Stroke
Test data  297  is  Stroke
Test data  298  is  normal
Test data  299  is  Stroke
Test data  300  is  normal
Test data  301  is  Stroke
Test data  302  is  Stroke
Test data  303  is  normal
Test data  304  is  Stroke
Test data  305  is  Stroke
Test data  306  is  Stroke
Test data  307  is  normal
Test data  308  is  Stroke
Test data  309  is  Stroke
Test data  310  is  Stroke
Test data  311  is  Stroke
Test data  312  is  Stroke
Test data  313  is  Stroke
Test data  314  is  Stroke
Test data  315  is  Stroke
Test data  316  is  normal
Test data  317  is  Stroke
Test data  318  is  Stroke
Test data  319  is  Stroke
Test data  320  is  Stroke
Test data  321  is  Stroke
Test data  322  is  Stroke
Test data  323  is  Stroke
Test data  324  is  normal
Test data  325  is  Stroke
Test data  326  is  Stroke
Test data  327  is  Stroke
Test data  328  is  Stroke
Test data  329  is  Stroke
Test data  330  is  normal
Test data  331  is  Stroke
Test data  332  is  normal
Test data  333  is  Stroke
Test data  334  is  Stroke
Test data  335  is  Stroke
Test data  336  is  Stroke
Test data  337  is  Stroke
Test data  338  is  Stroke
Test data  339  is  Stroke
Test data  340  is  normal
Test data  341  is  Stroke
Test data  342  is  Stroke
Test data  343  is  Stroke
Test data  344  is  Stroke
Test data  345  is  Stroke
Test data  346  is  Stroke
Test data  347  is  Stroke
Test data  348  is  Stroke
Test data  349  is  Stroke
Test data  350  is  Stroke
Test data  351  is  Stroke
Test data  352  is  Stroke
Test data  353  is  Stroke
Test data  354  is  Stroke
Test data  355  is  Stroke
Test data  356  is  Stroke
Test data  357  is  Stroke
Test data  358  is  Stroke
Test data  359  is  Stroke
Test data  360  is  Stroke
Test data  361  is  Stroke
Test data  362  is  Stroke
Test data  363  is  Stroke
Test data  364  is  Stroke
Test data  365  is  normal
Test data  366  is  Stroke
Test data  367  is  Stroke
Test data  368  is  Stroke
Test data  369  is  Stroke
Test data  370  is  Stroke
Test data  371  is  normal
Test data  372  is  Stroke
Test data  373  is  normal
Test data  374  is  Stroke
Test data  375  is  Stroke
Test data  376  is  Stroke
Test data  377  is  Stroke
Test data  378  is  normal
Test data  379  is  Stroke
Test data  380  is  Stroke
Test data  381  is  Stroke
Test data  382  is  Stroke
Test data  383  is  normal
Test data  384  is  normal
Test data  385  is  Stroke
Test data  386  is  Stroke
Test data  387  is  normal
Test data  388  is  normal
Test data  389  is  normal
Test data  390  is  Stroke
Test data  391  is  Stroke
Test data  392  is  normal
Test data  393  is  Stroke
Test data  394  is  Stroke
Test data  395  is  normal
Test data  396  is  Stroke
Test data  397  is  Stroke
Test data  398  is  Stroke
Test data  399  is  Stroke
Test data  400  is  normal
Test data  401  is  Stroke
Test data  402  is  normal
Test data  403  is  normal
Test data  404  is  normal
Test data  405  is  Stroke
Test data  406  is  Stroke
Test data  407  is  Stroke
Test data  408  is  normal
Test data  409  is  normal
Test data  410  is  Stroke
Test data  411  is  Stroke
Test data  412  is  Stroke
Test data  413  is  Stroke
Test data  414  is  Stroke
Test data  415  is  normal
Test data  416  is  Stroke
Test data  417  is  Stroke
Test data  418  is  Stroke
Test data  419  is  Stroke
Test data  420  is  Stroke
Test data  421  is  Stroke
Test data  422  is  Stroke
Test data  423  is  Stroke
Test data  424  is  Stroke
Test data  425  is  Stroke
Test data  426  is  Stroke
Test data  427  is  Stroke
Test data  428  is  Stroke
Test data  429  is  Stroke
Test data  430  is  normal
Test data  431  is  Stroke
Test data  432  is  normal
Test data  433  is  Stroke
Test data  434  is  normal
Test data  435  is  Stroke
Test data  436  is  Stroke
Test data  437  is  normal
Test data  438  is  Stroke
Test data  439  is  Stroke
Test data  440  is  Stroke
Test data  441  is  Stroke
Test data  442  is  Stroke
Test data  443  is  Stroke
Test data  444  is  Stroke
Test data  445  is  Stroke
Test data  446  is  Stroke
Test data  447  is  normal
Test data  448  is  normal
Test data  449  is  Stroke
Test data  450  is  Stroke
Test data  451  is  normal
Test data  452  is  normal
Test data  453  is  Stroke
Test data  454  is  Stroke
Test data  455  is  Stroke
Test data  456  is  Stroke
Test data  457  is  Stroke
Test data  458  is  Stroke
Test data  459  is  Stroke
Test data  460  is  Stroke
Test data  461  is  normal
Test data  462  is  Stroke
Test data  463  is  Stroke
Test data  464  is  normal
Test data  465  is  Stroke
Test data  466  is  Stroke
Test data  467  is  Stroke
Test data  468  is  normal
Test data  469  is  Stroke
Test data  470  is  Stroke
Test data  471  is  Stroke
Test data  472  is  Stroke
Test data  473  is  normal
Test data  474  is  Stroke
Test data  475  is  normal
Test data  476  is  Stroke
Test data  477  is  Stroke
Test data  478  is  Stroke
Test data  479  is  normal
Test data  480  is  Stroke
Test data  481  is  Stroke
Test data  482  is  Stroke
Test data  483  is  Stroke
Test data  484  is  Stroke
Test data  485  is  Stroke
Test data  486  is  Stroke
Test data  487  is  Stroke
Test data  488  is  Stroke
Test data  489  is  Stroke
Test data  490  is  Stroke
Test data  491  is  normal
Test data  492  is  Stroke
Test data  493  is  Stroke
Test data  494  is  normal
Test data  495  is  normal
Test data  496  is  Stroke
Test data  497  is  Stroke
Test data  498  is  Stroke
Test data  499  is  Stroke
Test data  500  is  Stroke
Test data  501  is  normal
Test data  502  is  Stroke
Test data  503  is  Stroke
Test data  504  is  normal
Test data  505  is  Stroke
Test data  506  is  normal
Test data  507  is  normal
Test data  508  is  normal
Test data  509  is  normal
Test data  510  is  normal
Test data  511  is  Stroke
Test data  512  is  Stroke
Test data  513  is  Stroke
Test data  514  is  Stroke
Test data  515  is  Stroke
Test data  516  is  normal
Test data  517  is  Stroke
Test data  518  is  Stroke
Test data  519  is  Stroke
Test data  520  is  Stroke
Test data  521  is  Stroke
Test data  522  is  Stroke
Test data  523  is  Stroke
Test data  524  is  Stroke
Test data  525  is  Stroke
Test data  526  is  normal
Test data  527  is  normal
Test data  528  is  Stroke
Test data  529  is  Stroke
Test data  530  is  Stroke
Test data  531  is  normal
Test data  532  is  normal
Test data  533  is  normal
Test data  534  is  Stroke
Test data  535  is  normal
Test data  536  is  normal
Test data  537  is  normal
Test data  538  is  Stroke
Test data  539  is  Stroke
Test data  540  is  Stroke
Test data  541  is  Stroke
Test data  542  is  normal
Test data  543  is  Stroke
Test data  544  is  Stroke
Test data  545  is  Stroke
Test data  546  is  normal
Test data  547  is  Stroke
Test data  548  is  Stroke
Test data  549  is  normal
Test data  550  is  normal
Test data  551  is  normal
Test data  552  is  Stroke
Test data  553  is  Stroke
Test data  554  is  normal
Test data  555  is  normal
Test data  556  is  Stroke
Test data  557  is  Stroke
Test data  558  is  Stroke
Test data  559  is  Stroke
Test data  560  is  normal
Test data  561  is  normal
Test data  562  is  Stroke
Test data  563  is  Stroke
Test data  564  is  normal
Test data  565  is  Stroke
Test data  566  is  normal
Test data  567  is  normal
Test data  568  is  Stroke
Test data  569  is  Stroke
Test data  570  is  Stroke
Test data  571  is  Stroke
Test data  572  is  Stroke
Test data  573  is  normal
Test data  574  is  Stroke
Test data  575  is  normal
Test data  576  is  Stroke
Test data  577  is  Stroke
Test data  578  is  normal
Test data  579  is  normal
Test data  580  is  normal
Test data  581  is  normal
Test data  582  is  Stroke
Test data  583  is  normal
Test data  584  is  Stroke
Test data  585  is  normal
Test data  586  is  Stroke
Test data  587  is  normal
Test data  588  is  Stroke
Test data  589  is  Stroke
Test data  590  is  Stroke
Test data  591  is  Stroke
Test data  592  is  Stroke
Test data  593  is  Stroke
Test data  594  is  Stroke
Test data  595  is  Stroke
Test data  596  is  Stroke
Test data  597  is  normal
Test data  598  is  Stroke
Test data  599  is  Stroke
Test data  600  is  Stroke
Test data  601  is  Stroke
Test data  602  is  Stroke
Test data  603  is  normal
Test data  604  is  normal
Test data  605  is  Stroke
Test data  606  is  normal
Test data  607  is  Stroke
Test data  608  is  normal
Test data  609  is  Stroke
Test data  610  is  Stroke
Test data  611  is  Stroke
Test data  612  is  Stroke
Test data  613  is  Stroke
Test data  614  is  Stroke
Test data  615  is  Stroke
Test data  616  is  Stroke
Test data  617  is  normal
Test data  618  is  normal
Test data  619  is  normal
Test data  620  is  Stroke
Test data  621  is  Stroke
Test data  622  is  normal
Test data  623  is  Stroke
Test data  624  is  Stroke
Test data  625  is  Stroke
Test data  626  is  Stroke
Test data  627  is  normal
Test data  628  is  Stroke
Test data  629  is  Stroke
Test data  630  is  Stroke
Test data  631  is  Stroke
Test data  632  is  Stroke
Test data  633  is  normal
Test data  634  is  Stroke
Test data  635  is  Stroke
Test data  636  is  normal
Test data  637  is  Stroke
Test data  638  is  Stroke
Test data  639  is  Stroke
Test data  640  is  normal
Test data  641  is  Stroke
Test data  642  is  Stroke
Test data  643  is  Stroke
Test data  644  is  Stroke
Test data  645  is  normal
Test data  646  is  Stroke
Test data  647  is  normal
Test data  648  is  Stroke
Test data  649  is  Stroke
Test data  650  is  Stroke
Test data  651  is  Stroke
Test data  652  is  Stroke
Test data  653  is  Stroke
Test data  654  is  Stroke
Test data  655  is  Stroke
Test data  656  is  Stroke
Test data  657  is  Stroke
Test data  658  is  Stroke
Test data  659  is  Stroke
Test data  660  is  Stroke
Test data  661  is  Stroke
Test data  662  is  normal
Test data  663  is  Stroke
Test data  664  is  normal
Test data  665  is  Stroke
Test data  666  is  normal
Test data  667  is  Stroke
Test data  668  is  Stroke
Test data  669  is  Stroke
Test data  670  is  normal
Test data  671  is  Stroke
Test data  672  is  Stroke
Test data  673  is  Stroke
Test data  674  is  Stroke
Test data  675  is  Stroke
Test data  676  is  Stroke
Test data  677  is  normal
Test data  678  is  Stroke
Test data  679  is  Stroke
Test data  680  is  Stroke
Test data  681  is  Stroke
Test data  682  is  Stroke
Test data  683  is  Stroke
Test data  684  is  Stroke
Test data  685  is  normal
Test data  686  is  Stroke
Test data  687  is  Stroke
Test data  688  is  Stroke
Test data  689  is  Stroke
Test data  690  is  Stroke
Test data  691  is  Stroke
Test data  692  is  Stroke
Test data  693  is  Stroke
Test data  694  is  Stroke
Test data  695  is  Stroke
Test data  696  is  Stroke
Test data  697  is  Stroke
Test data  698  is  Stroke
Test data  699  is  Stroke
Test data  700  is  Stroke
Test data  701  is  Stroke
Test data  702  is  Stroke
Test data  703  is  Stroke
Test data  704  is  normal
Test data  705  is  Stroke
Test data  706  is  Stroke
Test data  707  is  Stroke
Test data  708  is  Stroke
Test data  709  is  normal
Test data  710  is  Stroke
Test data  711  is  normal
Test data  712  is  Stroke
Test data  713  is  normal
Test data  714  is  Stroke
Test data  715  is  Stroke
Test data  716  is  normal
Test data  717  is  Stroke
Test data  718  is  Stroke
Test data  719  is  Stroke
Test data  720  is  Stroke
Test data  721  is  Stroke
Test data  722  is  Stroke
Test data  723  is  Stroke
Test data  724  is  normal
Test data  725  is  normal
Test data  726  is  Stroke
Test data  727  is  Stroke
Test data  728  is  Stroke
Test data  729  is  Stroke
Test data  730  is  Stroke
Test data  731  is  Stroke
Test data  732  is  Stroke
Test data  733  is  Stroke
Test data  734  is  Stroke
Test data  735  is  Stroke
Test data  736  is  Stroke
Test data  737  is  Stroke
Test data  738  is  Stroke
Test data  739  is  Stroke
Test data  740  is  Stroke
Test data  741  is  normal
Test data  742  is  Stroke
Test data  743  is  Stroke

In [120]:
print(confusion_matrix(y_test,y_pred))

[[ 421  179]
 [  20 1130]]

In [121]:
print("Accuracy for SGD Classifier : {}%".format(metrics.accuracy_score(y_test, y_pred)*100))

Accuracy for SGD Classifier : 88.62857142857142%

In [122]:
dt_classifier = DecisionTreeClassifier(max_features = i, random_state = 0)
dt_classifier.fit(X_train, y_train)

DecisionTreeClassifier(max_features=1749, random_state=0)

In [123]:
y_pred = dt_classifier.predict(X_test)
for i in range(0, len(y_pred)):
    i2=str(i)
    res=''
    if y_pred[i]==0:
        res='normal'
    elif y_pred[i]==1:
        res='Stroke'
    print('Test data ',i2 , ' is ',res)

Test data  0  is  normal
Test data  1  is  Stroke
Test data  2  is  Stroke
Test data  3  is  Stroke
Test data  4  is  Stroke
Test data  5  is  Stroke
Test data  6  is  Stroke
Test data  7  is  Stroke
Test data  8  is  Stroke
Test data  9  is  normal
Test data  10  is  Stroke
Test data  11  is  Stroke
Test data  12  is  Stroke
Test data  13  is  Stroke
Test data  14  is  Stroke
Test data  15  is  Stroke
Test data  16  is  normal
Test data  17  is  normal
Test data  18  is  Stroke
Test data  19  is  Stroke
Test data  20  is  Stroke
Test data  21  is  Stroke
Test data  22  is  Stroke
Test data  23  is  Stroke
Test data  24  is  Stroke
Test data  25  is  Stroke
Test data  26  is  Stroke
Test data  27  is  Stroke
Test data  28  is  Stroke
Test data  29  is  Stroke
Test data  30  is  normal
Test data  31  is  Stroke
Test data  32  is  Stroke
Test data  33  is  Stroke
Test data  34  is  Stroke
Test data  35  is  normal
Test data  36  is  Stroke
Test data  37  is  Stroke
Test data  38  is  Stroke
Test data  39  is  Stroke
Test data  40  is  Stroke
Test data  41  is  normal
Test data  42  is  Stroke
Test data  43  is  normal
Test data  44  is  normal
Test data  45  is  Stroke
Test data  46  is  normal
Test data  47  is  Stroke
Test data  48  is  normal
Test data  49  is  Stroke
Test data  50  is  Stroke
Test data  51  is  Stroke
Test data  52  is  normal
Test data  53  is  Stroke
Test data  54  is  normal
Test data  55  is  Stroke
Test data  56  is  Stroke
Test data  57  is  Stroke
Test data  58  is  Stroke
Test data  59  is  Stroke
Test data  60  is  Stroke
Test data  61  is  Stroke
Test data  62  is  Stroke
Test data  63  is  Stroke
Test data  64  is  Stroke
Test data  65  is  Stroke
Test data  66  is  Stroke
Test data  67  is  normal
Test data  68  is  normal
Test data  69  is  normal
Test data  70  is  Stroke
Test data  71  is  Stroke
Test data  72  is  Stroke
Test data  73  is  Stroke
Test data  74  is  Stroke
Test data  75  is  Stroke
Test data  76  is  Stroke
Test data  77  is  Stroke
Test data  78  is  Stroke
Test data  79  is  normal
Test data  80  is  Stroke
Test data  81  is  Stroke
Test data  82  is  normal
Test data  83  is  Stroke
Test data  84  is  Stroke
Test data  85  is  normal
Test data  86  is  Stroke
Test data  87  is  Stroke
Test data  88  is  normal
Test data  89  is  Stroke
Test data  90  is  Stroke
Test data  91  is  normal
Test data  92  is  Stroke
Test data  93  is  Stroke
Test data  94  is  Stroke
Test data  95  is  Stroke
Test data  96  is  Stroke
Test data  97  is  normal
Test data  98  is  normal
Test data  99  is  Stroke
Test data  100  is  Stroke
Test data  101  is  Stroke
Test data  102  is  Stroke
Test data  103  is  Stroke
Test data  104  is  Stroke
Test data  105  is  normal
Test data  106  is  Stroke
Test data  107  is  normal
Test data  108  is  Stroke
Test data  109  is  normal
Test data  110  is  Stroke
Test data  111  is  Stroke
Test data  112  is  Stroke
Test data  113  is  Stroke
Test data  114  is  Stroke
Test data  115  is  Stroke
Test data  116  is  Stroke
Test data  117  is  Stroke
Test data  118  is  normal
Test data  119  is  Stroke
Test data  120  is  Stroke
Test data  121  is  Stroke
Test data  122  is  Stroke
Test data  123  is  normal
Test data  124  is  normal
Test data  125  is  Stroke
Test data  126  is  normal
Test data  127  is  Stroke
Test data  128  is  normal
Test data  129  is  normal
Test data  130  is  normal
Test data  131  is  normal
Test data  132  is  Stroke
Test data  133  is  normal
Test data  134  is  Stroke
Test data  135  is  Stroke
Test data  136  is  Stroke
Test data  137  is  normal
Test data  138  is  Stroke
Test data  139  is  Stroke
Test data  140  is  normal
Test data  141  is  normal
Test data  142  is  Stroke
Test data  143  is  Stroke
Test data  144  is  normal
Test data  145  is  Stroke
Test data  146  is  Stroke
Test data  147  is  normal
Test data  148  is  Stroke
Test data  149  is  normal
Test data  150  is  Stroke
Test data  151  is  Stroke
Test data  152  is  normal
Test data  153  is  Stroke
Test data  154  is  normal
Test data  155  is  normal
Test data  156  is  Stroke
Test data  157  is  Stroke
Test data  158  is  Stroke
Test data  159  is  Stroke
Test data  160  is  normal
Test data  161  is  normal
Test data  162  is  Stroke
Test data  163  is  Stroke
Test data  164  is  Stroke
Test data  165  is  normal
Test data  166  is  normal
Test data  167  is  Stroke
Test data  168  is  Stroke
Test data  169  is  Stroke
Test data  170  is  normal
Test data  171  is  Stroke
Test data  172  is  normal
Test data  173  is  normal
Test data  174  is  Stroke
Test data  175  is  Stroke
Test data  176  is  Stroke
Test data  177  is  normal
Test data  178  is  Stroke
Test data  179  is  normal
Test data  180  is  Stroke
Test data  181  is  Stroke
Test data  182  is  Stroke
Test data  183  is  normal
Test data  184  is  Stroke
Test data  185  is  normal
Test data  186  is  normal
Test data  187  is  Stroke
Test data  188  is  Stroke
Test data  189  is  Stroke
Test data  190  is  Stroke
Test data  191  is  Stroke
Test data  192  is  normal
Test data  193  is  normal
Test data  194  is  Stroke
Test data  195  is  Stroke
Test data  196  is  Stroke
Test data  197  is  normal
Test data  198  is  normal
Test data  199  is  Stroke
Test data  200  is  Stroke
Test data  201  is  normal
Test data  202  is  Stroke
Test data  203  is  Stroke
Test data  204  is  Stroke
Test data  205  is  normal
Test data  206  is  normal
Test data  207  is  normal
Test data  208  is  Stroke
Test data  209  is  Stroke
Test data  210  is  Stroke
Test data  211  is  Stroke
Test data  212  is  normal
Test data  213  is  Stroke
Test data  214  is  normal
Test data  215  is  normal
Test data  216  is  normal
Test data  217  is  normal
Test data  218  is  Stroke
Test data  219  is  Stroke
Test data  220  is  normal
Test data  221  is  Stroke
Test data  222  is  normal
Test data  223  is  Stroke
Test data  224  is  normal
Test data  225  is  normal
Test data  226  is  normal
Test data  227  is  Stroke
Test data  228  is  Stroke
Test data  229  is  normal
Test data  230  is  normal
Test data  231  is  Stroke
Test data  232  is  normal
Test data  233  is  normal
Test data  234  is  Stroke
Test data  235  is  Stroke
Test data  236  is  Stroke
Test data  237  is  Stroke
Test data  238  is  Stroke
Test data  239  is  Stroke
Test data  240  is  Stroke
Test data  241  is  Stroke
Test data  242  is  Stroke
Test data  243  is  Stroke
Test data  244  is  Stroke
Test data  245  is  normal
Test data  246  is  Stroke
Test data  247  is  Stroke
Test data  248  is  Stroke
Test data  249  is  Stroke
Test data  250  is  Stroke
Test data  251  is  normal
Test data  252  is  Stroke
Test data  253  is  Stroke
Test data  254  is  normal
Test data  255  is  Stroke
Test data  256  is  Stroke
Test data  257  is  normal
Test data  258  is  normal
Test data  259  is  normal
Test data  260  is  normal
Test data  261  is  Stroke
Test data  262  is  Stroke
Test data  263  is  Stroke
Test data  264  is  Stroke
Test data  265  is  normal
Test data  266  is  normal
Test data  267  is  Stroke
Test data  268  is  normal
Test data  269  is  normal
Test data  270  is  Stroke
Test data  271  is  normal
Test data  272  is  Stroke
Test data  273  is  Stroke
Test data  274  is  Stroke
Test data  275  is  Stroke
Test data  276  is  normal
Test data  277  is  normal
Test data  278  is  Stroke
Test data  279  is  Stroke
Test data  280  is  Stroke
Test data  281  is  Stroke
Test data  282  is  Stroke
Test data  283  is  Stroke
Test data  284  is  Stroke
Test data  285  is  Stroke
Test data  286  is  Stroke
Test data  287  is  Stroke
Test data  288  is  Stroke
Test data  289  is  normal
Test data  290  is  Stroke
Test data  291  is  Stroke
Test data  292  is  Stroke
Test data  293  is  normal
Test data  294  is  Stroke
Test data  295  is  Stroke
Test data  296  is  Stroke
Test data  297  is  normal
Test data  298  is  normal
Test data  299  is  Stroke
Test data  300  is  normal
Test data  301  is  Stroke
Test data  302  is  Stroke
Test data  303  is  normal
Test data  304  is  Stroke
Test data  305  is  Stroke
Test data  306  is  Stroke
Test data  307  is  normal
Test data  308  is  Stroke
Test data  309  is  Stroke
Test data  310  is  Stroke
Test data  311  is  Stroke
Test data  312  is  Stroke
Test data  313  is  Stroke
Test data  314  is  Stroke
Test data  315  is  Stroke
Test data  316  is  normal
Test data  317  is  normal
Test data  318  is  Stroke
Test data  319  is  Stroke
Test data  320  is  Stroke
Test data  321  is  Stroke
Test data  322  is  Stroke
Test data  323  is  normal
Test data  324  is  normal
Test data  325  is  Stroke
Test data  326  is  Stroke
Test data  327  is  Stroke
Test data  328  is  Stroke
Test data  329  is  Stroke
Test data  330  is  normal
Test data  331  is  Stroke
Test data  332  is  normal
Test data  333  is  Stroke
Test data  334  is  Stroke
Test data  335  is  Stroke
Test data  336  is  Stroke
Test data  337  is  Stroke
Test data  338  is  Stroke
Test data  339  is  normal
Test data  340  is  normal
Test data  341  is  Stroke
Test data  342  is  normal
Test data  343  is  Stroke
Test data  344  is  normal
Test data  345  is  Stroke
Test data  346  is  Stroke
Test data  347  is  Stroke
Test data  348  is  Stroke
Test data  349  is  Stroke
Test data  350  is  Stroke
Test data  351  is  Stroke
Test data  352  is  Stroke
Test data  353  is  Stroke
Test data  354  is  Stroke
Test data  355  is  Stroke
Test data  356  is  Stroke
Test data  357  is  normal
Test data  358  is  Stroke
Test data  359  is  Stroke
Test data  360  is  Stroke
Test data  361  is  Stroke
Test data  362  is  Stroke
Test data  363  is  Stroke
Test data  364  is  Stroke
Test data  365  is  normal
Test data  366  is  Stroke
Test data  367  is  Stroke
Test data  368  is  Stroke
Test data  369  is  Stroke
Test data  370  is  normal
Test data  371  is  normal
Test data  372  is  Stroke
Test data  373  is  normal
Test data  374  is  normal
Test data  375  is  Stroke
Test data  376  is  Stroke
Test data  377  is  normal
Test data  378  is  normal
Test data  379  is  Stroke
Test data  380  is  Stroke
Test data  381  is  Stroke
Test data  382  is  Stroke
Test data  383  is  Stroke
Test data  384  is  normal
Test data  385  is  Stroke
Test data  386  is  Stroke
Test data  387  is  normal
Test data  388  is  normal
Test data  389  is  normal
Test data  390  is  Stroke
Test data  391  is  Stroke
Test data  392  is  normal
Test data  393  is  Stroke
Test data  394  is  Stroke
Test data  395  is  normal
Test data  396  is  Stroke
Test data  397  is  Stroke
Test data  398  is  Stroke
Test data  399  is  Stroke
Test data  400  is  normal
Test data  401  is  Stroke
Test data  402  is  normal
Test data  403  is  normal
Test data  404  is  normal
Test data  405  is  normal
Test data  406  is  normal
Test data  407  is  normal
Test data  408  is  normal
Test data  409  is  normal
Test data  410  is  Stroke
Test data  411  is  Stroke
Test data  412  is  Stroke
Test data  413  is  Stroke
Test data  414  is  Stroke
Test data  415  is  normal
Test data  416  is  Stroke
Test data  417  is  Stroke
Test data  418  is  Stroke
Test data  419  is  Stroke
Test data  420  is  normal
Test data  421  is  Stroke
Test data  422  is  Stroke
Test data  423  is  Stroke
Test data  424  is  Stroke
Test data  425  is  normal
Test data  426  is  Stroke
Test data  427  is  Stroke
Test data  428  is  Stroke
Test data  429  is  Stroke
Test data  430  is  normal
Test data  431  is  Stroke
Test data  432  is  normal
Test data  433  is  Stroke
Test data  434  is  normal
Test data  435  is  Stroke
Test data  436  is  normal
Test data  437  is  normal
Test data  438  is  Stroke
Test data  439  is  Stroke
Test data  440  is  Stroke
Test data  441  is  Stroke
Test data  442  is  Stroke
Test data  443  is  Stroke
Test data  444  is  Stroke
Test data  445  is  Stroke
Test data  446  is  Stroke
Test data  447  is  normal
Test data  448  is  normal
Test data  449  is  Stroke
Test data  450  is  Stroke
Test data  451  is  Stroke
Test data  452  is  normal
Test data  453  is  Stroke
Test data  454  is  Stroke
Test data  455  is  normal
Test data  456  is  Stroke
Test data  457  is  Stroke
Test data  458  is  Stroke
Test data  459  is  Stroke
Test data  460  is  Stroke
Test data  461  is  normal
Test data  462  is  Stroke
Test data  463  is  Stroke
Test data  464  is  normal
Test data  465  is  Stroke
Test data  466  is  Stroke
Test data  467  is  Stroke
Test data  468  is  Stroke
Test data  469  is  Stroke
Test data  470  is  Stroke
Test data  471  is  Stroke
Test data  472  is  Stroke
Test data  473  is  normal
Test data  474  is  Stroke
Test data  475  is  normal
Test data  476  is  normal
Test data  477  is  Stroke
Test data  478  is  Stroke
Test data  479  is  normal
Test data  480  is  Stroke
Test data  481  is  Stroke
Test data  482  is  Stroke
Test data  483  is  Stroke
Test data  484  is  Stroke
Test data  485  is  Stroke
Test data  486  is  Stroke
Test data  487  is  Stroke
Test data  488  is  Stroke
Test data  489  is  Stroke
Test data  490  is  Stroke
Test data  491  is  normal
Test data  492  is  Stroke
Test data  493  is  Stroke
Test data  494  is  normal
Test data  495  is  normal
Test data  496  is  Stroke
Test data  497  is  Stroke
Test data  498  is  Stroke
Test data  499  is  normal
Test data  500  is  Stroke
Test data  501  is  normal
Test data  502  is  Stroke
Test data  503  is  Stroke
Test data  504  is  normal
Test data  505  is  Stroke
Test data  506  is  normal
Test data  507  is  normal
Test data  508  is  normal
Test data  509  is  normal
Test data  510  is  normal
Test data  511  is  Stroke
Test data  512  is  Stroke
Test data  513  is  Stroke
Test data  514  is  normal
Test data  515  is  Stroke
Test data  516  is  normal
Test data  517  is  normal
Test data  518  is  Stroke
Test data  519  is  Stroke
Test data  520  is  normal
Test data  521  is  Stroke
Test data  522  is  Stroke
Test data  523  is  Stroke
Test data  524  is  Stroke
Test data  525  is  Stroke
Test data  526  is  normal
Test data  527  is  normal
Test data  528  is  Stroke
Test data  529  is  Stroke
Test data  530  is  Stroke
Test data  531  is  Stroke
Test data  532  is  normal
Test data  533  is  normal
Test data  534  is  Stroke
Test data  535  is  normal
Test data  536  is  normal
Test data  537  is  normal
Test data  538  is  Stroke
Test data  539  is  Stroke
Test data  540  is  Stroke
Test data  541  is  normal
Test data  542  is  normal
Test data  543  is  Stroke
Test data  544  is  Stroke
Test data  545  is  Stroke
Test data  546  is  normal
Test data  547  is  Stroke
Test data  548  is  Stroke
Test data  549  is  normal
Test data  550  is  normal
Test data  551  is  normal
Test data  552  is  Stroke
Test data  553  is  Stroke
Test data  554  is  normal
Test data  555  is  normal
Test data  556  is  Stroke
Test data  557  is  Stroke
Test data  558  is  Stroke
Test data  559  is  Stroke
Test data  560  is  normal
Test data  561  is  normal
Test data  562  is  Stroke
Test data  563  is  Stroke
Test data  564  is  normal
Test data  565  is  Stroke
Test data  566  is  normal
Test data  567  is  normal
Test data  568  is  normal
Test data  569  is  Stroke
Test data  570  is  Stroke
Test data  571  is  Stroke
Test data  572  is  Stroke
Test data  573  is  normal
Test data  574  is  Stroke
Test data  575  is  normal
Test data  576  is  Stroke
Test data  577  is  Stroke
Test data  578  is  normal
Test data  579  is  normal
Test data  580  is  normal
Test data  581  is  normal
Test data  582  is  Stroke
Test data  583  is  Stroke
Test data  584  is  Stroke
Test data  585  is  normal
Test data  586  is  Stroke
Test data  587  is  normal
Test data  588  is  Stroke
Test data  589  is  Stroke
Test data  590  is  Stroke
Test data  591  is  Stroke
Test data  592  is  Stroke
Test data  593  is  Stroke
Test data  594  is  Stroke
Test data  595  is  Stroke
Test data  596  is  Stroke
Test data  597  is  normal
Test data  598  is  Stroke
Test data  599  is  Stroke
Test data  600  is  normal
Test data  601  is  Stroke
Test data  602  is  normal
Test data  603  is  normal
Test data  604  is  normal
Test data  605  is  Stroke
Test data  606  is  normal
Test data  607  is  Stroke
Test data  608  is  normal
Test data  609  is  Stroke
Test data  610  is  Stroke
Test data  611  is  Stroke
Test data  612  is  Stroke
Test data  613  is  Stroke
Test data  614  is  Stroke
Test data  615  is  Stroke
Test data  616  is  Stroke
Test data  617  is  normal
Test data  618  is  normal
Test data  619  is  normal
Test data  620  is  Stroke
Test data  621  is  Stroke
Test data  622  is  normal
Test data  623  is  Stroke
Test data  624  is  Stroke
Test data  625  is  Stroke
Test data  626  is  Stroke
Test data  627  is  normal
Test data  628  is  Stroke
Test data  629  is  Stroke
Test data  630  is  Stroke
Test data  631  is  Stroke
Test data  632  is  Stroke
Test data  633  is  normal
Test data  634  is  Stroke
Test data  635  is  Stroke
Test data  636  is  normal
Test data  637  is  Stroke
Test data  638  is  Stroke
Test data  639  is  normal
Test data  640  is  normal
Test data  641  is  Stroke
Test data  642  is  Stroke
Test data  643  is  Stroke
Test data  644  is  Stroke
Test data  645  is  normal
Test data  646  is  Stroke
Test data  647  is  normal
Test data  648  is  Stroke
Test data  649  is  Stroke
Test data  650  is  Stroke
Test data  651  is  Stroke
Test data  652  is  Stroke
Test data  653  is  Stroke
Test data  654  is  Stroke
Test data  655  is  Stroke
Test data  656  is  Stroke
Test data  657  is  Stroke
Test data  658  is  Stroke
Test data  659  is  Stroke
Test data  660  is  Stroke
Test data  661  is  Stroke
Test data  662  is  normal
Test data  663  is  Stroke
Test data  664  is  normal
Test data  665  is  Stroke
Test data  666  is  normal
Test data  667  is  normal
Test data  668  is  normal
Test data  669  is  Stroke
Test data  670  is  normal
Test data  671  is  Stroke
Test data  672  is  Stroke
Test data  673  is  Stroke
Test data  674  is  Stroke
Test data  675  is  Stroke
Test data  676  is  Stroke
Test data  677  is  normal
Test data  678  is  Stroke
Test data  679  is  Stroke
Test data  680  is  Stroke
Test data  681  is  Stroke
Test data  682  is  Stroke
Test data  683  is  Stroke
Test data  684  is  Stroke
Test data  685  is  normal
Test data  686  is  Stroke
Test data  687  is  normal
Test data  688  is  Stroke
Test data  689  is  Stroke
Test data  690  is  Stroke
Test data  691  is  normal
Test data  692  is  Stroke
Test data  693  is  Stroke
Test data  694  is  Stroke
Test data  695  is  Stroke
Test data  696  is  Stroke
Test data  697  is  Stroke
Test data  698  is  Stroke
Test data  699  is  Stroke
Test data  700  is  Stroke
Test data  701  is  Stroke
Test data  702  is  Stroke
Test data  703  is  Stroke
Test data  704  is  normal
Test data  705  is  Stroke
Test data  706  is  normal
Test data  707  is  Stroke
Test data  708  is  Stroke
Test data  709  is  normal
Test data  710  is  Stroke
Test data  711  is  normal
Test data  712  is  normal
Test data  713  is  normal
Test data  714  is  Stroke
Test data  715  is  normal
Test data  716  is  normal
Test data  717  is  Stroke
Test data  718  is  normal
Test data  719  is  Stroke
Test data  720  is  Stroke
Test data  721  is  Stroke
Test data  722  is  Stroke
Test data  723  is  Stroke
Test data  724  is  normal
Test data  725  is  normal
Test data  726  is  Stroke
Test data  727  is  Stroke
Test data  728  is  Stroke
Test data  729  is  Stroke
Test data  730  is  Stroke
Test data  731  is  Stroke
Test data  732  is  Stroke
Test data  733  is  Stroke
Test data  734  is  normal
Test data  735  is  Stroke
Test data  736  is  Stroke
Test data  737  is  Stroke
Test data  738  is  Stroke
Test data  739  is  Stroke
Test data  740  is  Stroke
Test data  741  is  normal
Test data  742  is  Stroke
Test data  743  is  Stroke

In [124]:
print(confusion_matrix(y_test,y_pred))

[[ 528   72]
 [   0 1150]]

In [125]:
print("Accuracy for Decision Tree Classifier is {}%".format(metrics.accuracy_score(y_test, y_pred)*100))

Accuracy for Decision Tree Classifier is 95.88571428571429%

In [126]:
# Naive Bayes example
gnb = GaussianNB()
gnb.fit(X_train, y_train)
y_pred = gnb.predict(X_test)

# Now add this:
print("Naive Bayes Results:")
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred, target_names=['Normal', 'Stroke']))

Naive Bayes Results:
[[ 352  248]
 [  85 1065]]
              precision    recall  f1-score   support

      Normal       0.81      0.59      0.68       600
      Stroke       0.81      0.93      0.86      1150

    accuracy                           0.81      1750
   macro avg       0.81      0.76      0.77      1750
weighted avg       0.81      0.81      0.80      1750

In [127]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix

# Create and train the model
knn = KNeighborsClassifier(n_neighbors=7)
knn.fit(X_train, y_train)

# Make predictions
y_pred = knn.predict(X_test)

# Print results
print("K-Nearest Neighbors (KNN) Results:")
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=['Normal', 'Stroke']))

K-Nearest Neighbors (KNN) Results:

Confusion Matrix:
[[ 328  272]
 [  17 1133]]

Classification Report:
              precision    recall  f1-score   support

      Normal       0.95      0.55      0.69       600
      Stroke       0.81      0.99      0.89      1150

    accuracy                           0.83      1750
   macro avg       0.88      0.77      0.79      1750
weighted avg       0.86      0.83      0.82      1750